### ISSUE TITLE
Opening a new browser window will lose focus in A-S

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#2554] opened 2017-05-04 22:30 UTC
Reported by @st3fan,

> I have a desktop bug: When I create a new window, neither location field or Activity Stream search field have focus, so I have to click or hit Command-L. New tabs do focus on the location field.

**Comment by k88hudson** [comment] 2017-05-05 20:12
This is for the test pilot add-on, right?

**Comment by ncloudioj** [comment] 2017-05-05 20:31
Yep, it's reproducible there.

**Comment by jaredkerim** [comment] 2017-05-08 18:15
Because this may impact the SHIELD study let's fix this if it's quick and easy.

**Comment by sarracini** [comment] 2017-05-11 17:17
Dupe of #2007

**Closed by sarracini** 2017-05-11 17:17 UTC
Labels: MVP, P1
