### ISSUE TITLE
Images are missing from Highlights

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#1577] opened 2016-10-18 14:45 UTC
**[Affected versions]:**
-Nightly 45 and up
-Activity Stream 1.1.4-dev

**[Affected Platforms]:**
-All Windows

**[Prerequisites]:**
-Latest Activity Stream add-on version (1.1.4-dev) was previously installed on a profile with browsing history.

**[Steps to reproduce]:**
1. Start the browser with the profile from prerequisites.
2. Open a new tab and observe the Highlights from New Tab page.

**[Expected results]:**
-Spotlight image is displayed for items that are in Highlights tiles.

**[Actual results]:**
-The spotlight image is not displayed for Highlights, only the favicon is displayed.

**[Notes]:**
-Attached a screenshot of the issue:
![highlights without spotlight image](https://cloud.githubusercontent.com/assets/9248513/19475854/db06b58e-953e-11e6-8e19-8f0312ca0abf.jpg)

**Comment by dmose** [comment] 2016-10-18 15:20
I believe this is a side-effect of the caching architecture.   Try opening another tab or two after the first one.  Do they have this problem or do they have real images?

**Comment by Softvision-VladBacia** [comment] 2016-10-19 08:31
@dmose , with the today build I cannot see this issue. The spotlight images are correctly displayed.

**Comment by jaredkerim** [comment] 2016-10-19 15:51
I am able to reproduce this today using the latest master.  Steps to reproduce:

1. Start Activity Stream on an empty profile
2. Go to http://news.ycombinator.com/
3. Open 10 links
4. Open a new tab, observe the following:

<img width="1440" alt="screenshot 2016-10-19 11 47 45" src="https://cloud.githubusercontent.com/assets/119884/19526277/e88a528e-95f1-11e6-84fe-f2d9b31c2ba8.png">

https://gist.github.com/jaredkerim/080190f226be38d763b8176adc5e0235

5. Open a new tab again (after metadata fetch has completed) and observe the following:

<img width="1440" alt="screenshot 2016-10-19 11 49 23" src="https://cloud.githubusercontent.com/assets/119884/19526335/1b8d3c3c-95f2-11e6-90fe-4296a28cf459.png">

https://gist.github.com/jaredkerim/40f9ed38d317f8d71a752f0175fc6e20

**Comment by sarracini** [comment] 2016-10-27 14:41
Ooops this got closed when #1639 merged, but it might not be closed yet - re-opening this

**Comment by sarracini** [comment] 2016-10-27 16:57
Im fairly certain this will no longer happen with the fix from #1639. I'll close this and we can re-open if we see it again

**Comment by k88hudson** [comment] 2016-10-28 17:04
I'm still seeing this on dev, with the following errors in console:
```
Error: Error(s) encountered during statement execution: UNIQUE constraint failed: page_metadata.cache_key
Stack trace:
ConnectionData.prototype<._executeStatement/pending<.handleCompletion@resource://gre/modules/Sqlite.jsm:807:25
Sqlite.jsm:648
Error(s) encountered during statement execution: UNIQUE constraint failed: page_metadata.cache_key
Sqlite.jsm:807
MetadataStore failed to insert metadata: Error(s) encountered during statement execution: UNIQUE constraint failed: page_metadata.cache_key
MetadataStore.js:285
Error: Error(s) encountered during statement execution: UNIQUE constraint failed: page_metadata.cache_key
Stack trace:
ConnectionData.prototype<._executeStatement/pending<.handleCompletion@resource://gre/modules/Sqlite.jsm:807:25
Sqlite.jsm:648
Error(s) encountered during statement execution: UNIQUE constraint failed: page_metadata.cache_key
Sqlite.jsm:807
MetadataStore failed to insert metadata: Error(s) encountered during statement execution: UNIQUE constraint failed: page_metadata.cache_key
MetadataStore.js:285
Error: Error(s) encountered during statement execution: UNIQUE constraint failed: page_metadata.cache_key
Stack trace:
ConnectionData.prototype<._executeStatement/pending<.handleCompletion@resource://gre/modules/Sqlite.jsm:807:25
Sqlite.jsm:648
Error(s) encountered during statement execution: UNIQUE constraint failed: page_metadata.cache_key
```

Note that in the Old Highlights query, the same sites DO have images

![](https://k88hudson-screenshots.s3.amazonaws.com/screen-shots/Screen_Shot_2016-10-28_at_1.03.42_PM.png)

**Comment by k88hudson** [comment] 2016-10-28 21:50
Alright, I managed to track down something that might help:

The problem seems to be that an error is being thrown in `asyncGetMetadataByCacheKey` (https://github.com/mozilla/activity-stream/blob/master/addon/MetadataStore.js#L445) but is not logged or handled. The error I get is the following:

```
Error: Error(s) encountered during statement execution: near "asti": syntax error
```
And the cache key it is failing on is `"winealign.com/wines/92217-Pico-Maccario-Lavignone-Barbera-D'asti-2014"`

I'm guessing it might be the `'` 😭

**Comment by rlr** [comment] 2016-10-28 21:54
ohhhh nooooooo. that makes sense though. I'll try to see if that's what's happening on my end too. awesome find!

**Comment by rlr** [comment] 2016-10-31 12:49
Yep, I found I have a `'` in my list of cache keys too. The problem here is that we aren't properly parameterizing (is that a word?) the sql query. I'll change this queries to do it properly and hopefully that fixes all the things. Great find @k88hudson, thank you!

**Closed** 2016-11-01 14:27 UTC
Labels: Critical, Has PR, P1
