### ISSUE TITLE
All recently bookmarked items should make an apearance on NewTab.

### ISSUE THREAD

**Issue by bryanbell** [mozilla/activity-stream#1794] opened 2016-11-15 16:48 UTC
There is a class of bookmarked content that never seems to make it to the New Tab. This is probably content that might not have "good enough" imagery. 

For example, this doesn't show on New Tab (for me). https://www.dropbox.com/s/nh706j38jyoz26u/SnoozeTabs%20UI%20v2.1.pdf?dl=0

In short, anything a user bookmarks would make the cut.

**Comment by k88hudson** [comment] 2016-11-15 18:49
I think @Mardak  is working on this already in https://github.com/mozilla/activity-stream/issues/1670, right?

**Comment by Mardak** [comment] 2016-11-15 19:26
Do those bookmarks eventually show up after 15 minutes? If so, then dupe of #1670.

"Anything a user bookmarks" is opposite of the current logic of only showing bookmarks created within 3 days and haven't been visited more than 3 times.

**Comment by ncloudioj** [comment] 2016-11-18 16:03
Seeing the same issue here. Haven't seen any bookmarks in my highlights for awhile, even the recent bookmarked links didn't show up.

**Comment by bryanbell** [comment] 2016-11-18 17:31
@Mardak I'm not suggesting that it should look back farther that 3 days, I'm pointing out that certain things that people can bookmark are being excluded for unknown reason and that should be fixed.

**Comment by k88hudson** [comment] 2016-11-21 19:22
One option here might be to having bookmarks be a separate data source/feed from weighted highlights, with a separate query etc. to avoid having to run the entire highlights weighting query every time something is bookmarked. That way, we could have a different update cycle, different rules about what to show when, etc.

**Comment by jaredkerim** [comment] 2016-11-22 17:42
It was suggested that we implement this as an experiment to measure how this affects engagement/interaction.

**Comment by Mardak** [comment] 2016-11-22 23:37
Anyone have a different link to test with? The one provided in the original comment works fine for me now -- I would assume it's the local metadata change causing there to be an image right away allowing the bookmark to be shown.

<img width="233" alt="image" src="https://cloud.githubusercontent.com/assets/438537/20546383/94f7e38c-b0c9-11e6-954c-6443275a8bc2.png">

**Comment by ncloudioj** [comment] 2016-11-23 21:05
@Mardak It still couldn't show the recently added bookmarks in the highlights. (I'm on dev, running both on Windows and MacOs) . The bookmarked links were just some random pages, i.e. newegg.ca, amazon.com etc.

**Closed** 2016-12-01 14:48 UTC
Labels: P1
