### ISSUE TITLE
Bug 1302733 - Loading spinner and text are flickering when a search is in progress in Activity Stream Timeline page

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#1286] opened 2016-09-14 14:10 UTC
via https://bugzilla.mozilla.org/show_bug.cgi?id=1302733 

---
[Summary]:
Min-Vid Player position is affected by the resizing of the browser window

[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.1.3-dev

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Activity Stream add-on version (1.1.3-dev ) was previously installed on an old profile with a lot o data (bookmarks + browsing history).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Click on "Activity Stream Timeline" button from browser toolbar.
3. Type some characters in the Activity Stream search bar.
4. wait for the search to be performed.

[Expected result]:
- While the search is performed, the loading spinner and text are displayed all the time.

[Actual result]:
- While the search is performed, the loading spinner and text are flickering.

[Additional Notes]:
- [Here](https://bug1302733.bmoattachments.org/attachment.cgi?id=8791202) is a screen recording of the issue.
- Also there is an error in the browser console while the search is performed. Picture [here](https://bug1302733.bmoattachments.org/attachment.cgi?id=8791203).

**Comment by jaredkerim** [comment] 2016-09-19 17:26
Closing as a duplicate of #1302

**Closed by jaredkerim** 2016-09-19 17:26 UTC
