### ISSUE TITLE
z-index issue with snippet

### ISSUE THREAD

**Issue by johngruen** [mozilla/activity-stream#3518] opened 2017-09-18 13:15 UTC
<img width="1156" alt="screen shot 2017-09-18 at 9 15 30 am" src="https://user-images.githubusercontent.com/3323249/30543662-f164a686-9c51-11e7-87b4-e836815aafd4.png">

**Comment by piatra** [comment] 2017-09-18 13:30
Duplicate of https://github.com/mozilla/activity-stream/issues/3504.

**Closed by piatra** 2017-09-18 13:30 UTC
