### ISSUE TITLE
Add ability to search my own Activity Stream

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#743] opened 2016-05-24 22:13 UTC
Currently in Activity Stream there is no way for me to search my own browsing history.
If I open a new tab, there is a "Search the Web" search field, which [not surprisingly] searches The Internet using my preferred search provider.

... But there is no way to search all my past browsing history for that awesome lentils recipe that I found 2 weeks ago. I'm stuck re-searching for lentils, or infinite scrolling my history and hoping I can find that elusive recipe.

Not sure if we said we could add a pinned search field to the Timeline page which would search your personal history (presumably just titles or whatever we store), or if that adds some inconsistency with search behaviors between the new tab page and timeline page.

**Comment by edmoz** [comment] 2016-06-23 20:27
dupe of #416

**Closed by edmoz** 2016-06-23 20:27 UTC
Labels: Design feedback needed, Search
