### ISSUE TITLE
TopSite titles are getting clipped

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#2508] opened 2017-04-27 20:01 UTC
<img width="387" alt="image" src="https://cloud.githubusercontent.com/assets/25276/25014660/aaeb3350-2046-11e7-9409-ab072466fdc0.png">

**Comment by jaredkerim** [comment] 2017-05-01 18:47
Closing as a duplicate of #2421

**Closed by jaredkerim** 2017-05-01 18:47 UTC
