### ISSUE TITLE
If a top site requires basic auth/password, opening a new tab triggers login dialogue

### ISSUE THREAD

**Issue by rikkit** [mozilla/activity-stream#2199] opened 2017-03-02 09:40 UTC
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1392151

The request to get a thumbnail or favicon for the site triggers basic authentication, but just opening a new tab doesn't mean that I want to log in to that site.

# Reproduce
1. Have a site requiring basic auth in your activity stream's top sites list
2. Clear logins from Firefox/ restart computer
3. Open a new tab
4. You'll be prompted to login to the site requiring basic auth.
5. After login, the favicon will load for this site.

# Found on
Firefox 53.0a2 (2017-03-01) (32-bit)
Windows 10 14986.1001

**Comment by ncloudioj** [comment] 2017-03-08 17:12
Thanks for reporting this issue! @rikkit

This issue was caused by the fact that we are storing the favicon URLs instead of URIs in the page metadata database. If user clears the logins info for the sites with basic auth in the Topsites, Firefox will try to fetch the favicon, which might be behind the basic auth protection as well.

We can solve this issue by storing favicon URI in the metadata database at the cost of the higher disk usage. Given that metadata database employs an active data expiry policy, the database should not grow without bound.

**Comment by ncloudioj** [comment] 2017-03-08 19:11
In a follow-up team discussion, we decided to put this fix on hold since there is some similar work in progress on the favicon for Places database. Converting favicon URLs into data URIs inside the add-on is considered to be both redundant and inefficient.

Moving this issue to backlog for now.

**Comment by jaredkerim** [comment] 2017-03-13 19:39
@rikkit Thanks for bringing this up, this has been a known issue with Activity Stream since the beginning.  As @ncloudioj said, we have scoped out a solution to this for the Firefox native version of Activity Stream, so I don't think we will ever explicitly solve this issue for the addon version.

We're going to keep this ticket open as a way to track that progress, and so I want to add a few additional points about this for future reference.

There are three primary concerns about fetching remote resources with each activity stream session:

1) Performance - fetching remote resources necessarily consumes resources
2) Behaviour - fetching remote resources can cause bizarre behaviours such as the basic auth flow you're describing
3) Security - fetching unvalidated remote resources can result in malicious payloads being injected into users browser sessions

For each and all of these reasons, we will need to address these issues before we land Activity Stream into Firefox.  When the PlacesDB adds columns for storing low res icons, high res icons, and preview images, we can switch to that and prevent Activity Stream from fetching any remote resources.

**Comment by rikkit** [comment] 2017-03-14 15:22
Thanks @jaredkerim. Just wanted to say I've stopped trialling Activity Stream on my work computer because of this issue; I use Firefox all day at work and kept getting prompted for the same site. Thanks for your efforts and hopefully I'll be trialling again in future 👍

**Comment by Mardak** [comment] 2017-08-21 15:33
@ncloudioj is this issue still blocked? And if so, will it be done for Firefox 57? If not, can we work around this issue another way for 57?

**Comment by ncloudioj** [comment] 2017-08-21 15:53
@Mardak This issue should not affect the system addon. Since, unlike the Test Pilot addon, it doesn't rely on favicon URLs any more for Top sites, and would not attempt to fetch the favicons at the point of Top sites rendering.

I think we can close this issue. @sarracini Could you confirm this, please?

**Comment by Mardak** [comment] 2017-08-21 16:32
Okay, if we close this, we'll need to open a new issue for thumbnails https://bugzilla.mozilla.org/show_bug.cgi?id=1392151

**Comment by ncloudioj** [comment] 2017-08-21 16:55
Oops, thumbnails. Let's keep this one then.

 I think fixing following two bugs will mitigate this issue, https://github.com/mozilla/activity-stream/issues/2739 and https://github.com/mozilla/activity-stream/issues/3113

**Comment by Mardak** [comment] 2017-08-21 17:15
Mmm. I'm not sure about those two other issues fixing the login issue. The rich icons are only useful if the site has that metadata, and I doubt say a local router page is going to put an opengraph thumbnail image. And if a page with login is in your top sites, it's quite likely that it's a site with high frecency in the common case.

**Comment by ncloudioj** [comment] 2017-08-21 17:34
That's true. We'll still need to fix the screenshot code to properly handle the HTTP basic authentication. I was not saying that fixing those issues will *fix* the login issue, but just mitigate this issue. My apology for the confusion :)

**Comment by Mardak** [comment] 2017-08-31 02:44
Looks like the recent bugzilla bug was a Test Pilot issue

**Closed by Mardak** 2017-08-31 02:44 UTC
Labels: Bug, Bugzilla
