### ISSUE TITLE
Highlights not showing images when browser is offline

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1854] opened 2016-12-07 22:05 UTC
If I open a new tab when my browser is disconnected from the internet, I have metadata for every highlight but am not able to fetch images which are not locally cached, which shows a semi degraded activity stream page:

<img width="1440" alt="screenshot 2016-12-07 12 00 12" src="https://cloud.githubusercontent.com/assets/119884/20988550/63011e68-bc75-11e6-8d39-2176dd6c9702.png">

**Comment by sarracini** [comment] 2017-01-30 16:49
Closing this as a dupe of #2032

**Closed by sarracini** 2017-01-30 16:49 UTC
Labels: P2
