### ISSUE TITLE
In Private Browsing window, Activity Stream's toolbar button just opens an about:privatebrowsing tab

### ISSUE THREAD

**Issue by dholbert** [mozilla/activity-stream#841] opened 2016-06-12 22:03 UTC
STR:
 1. Open a Private Browsing window.
 2. Try clicking Activity Stream toolbar button.

ACTUAL RESULTS:
An about:privatebrowsing tab opens up.  This feels a bit unexpected / a bit of a non-sequitor.

EXPECTED RESULTS:
* I should be taken to a page that says Activity Stream is disabled in Private Browsing mode.
* ...OR, better: the Activity Stream toolbar button should just be hidden in Private Browsing windows. (The "Test Pilot" toolbar button is hidden in PB windows; seems like Activity Stream's button should hide as well.)

**Comment by Standard8** [comment] 2016-07-28 14:34
In #538, there was a change to enable the private-browsing module of the add-on SDK, so that where the PageMod happens (the bit that actually loads newtab) it would be able to detect if you're in a private browsing window or not, and force it to load the default private browsing tab page as appropriate.

However, the side-effect of enabling the private-browsing module, appears to be that the button is no longer hidden in private browsing mode - the add-on SDK assumes that because the add-on can handle private browsing, it needs the button in that window. There is no option in the SDK to hide the button per window, only to disable it.

[PageMod is private browsing module aware](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/private-browsing#Opting_into_private_browsing), and won't run for private windows. Due to this, we end up with just a blank page as we're overriding the new tab url.

Additionally the [NewTabURL module](https://dxr.mozilla.org/mozilla-central/source/browser/components/newtab/NewTabURL.jsm) provided by Firefox doesn't give us the option for only overriding it in non-private browsing mode.

So for the ideal option of hiding the button, that doesn't seem possible unless we do some DOM manipulation which is probably a bad idea.

I guess it is possible we could get the ActionButton of the sdk changed to supply a hide in private browsing mode option, although I don't know how that fits with the work going on with WebExtensions.

Also, I think @k88hudson might have mentioned something about not being happy with how the new tab page is overridden, so maybe fixing will depend on whatever that solution is.

**Comment by sarracini** [comment] 2016-10-21 19:11
Closing this as this working as intended

**Closed by sarracini** 2016-10-21 19:11 UTC
Labels: P2
