### ISSUE TITLE
Sometimes trending cards don't display times

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#954] opened 2016-07-22 19:29 UTC
![activity_stream](https://cloud.githubusercontent.com/assets/557895/17068714/781b6748-5007-11e6-8b3a-50f190f12c29.png)

![activity_stream](https://cloud.githubusercontent.com/assets/557895/17068735/98d344f6-5007-11e6-9ad4-3895435ada99.png)

![activity_stream](https://cloud.githubusercontent.com/assets/557895/17068747/a69124c8-5007-11e6-9d7e-0c05c7e54673.png)

Related: #953

**Comment by sarracini** [comment] 2016-07-22 19:48
This is by design - some timestamps come back from pocket as ```0``` as in pocket doesn't know when it was published so in that case we don't show a timestamp at all. Closing this

**Closed by sarracini** 2016-07-22 19:48 UTC
