### ISSUE TITLE
Not playing nice with containers

### ISSUE THREAD

**Issue by sole** [mozilla/activity-stream#2298] opened 2017-03-22 12:20 UTC
Hey, just a heads up, it seems like this experiment doesn't quite work well with the new containers feature. I filed [a bug in Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1348771) and they recognised it was actually an Activity stream issue.

**Comment by sarracini** [comment] 2017-03-22 14:40
Dupe of #1389

**Closed** 2017-03-22 14:40 UTC
