### ISSUE TITLE
Collect addon errors via Sentry?

### ISSUE THREAD

**Issue by oyiptong** [mozilla/activity-stream#1016] opened 2016-08-02 17:37 UTC
Would be useful to keep track of errors occurring in the addon

**Comment by oyiptong** [comment] 2016-08-02 17:39
@edmoz could we see if we can add that to our TOS?

**Comment by pdehaan** [comment] 2016-08-22 17:14
Ref: **Add Sentry tooling to front-end** #747

@edmoz to follow up w/ Legal today, re: adding Sentry.

**Comment by edmoz** [comment] 2016-08-22 18:00
Ping'd legal again today.  I believe next step is to get an update PN drafted.

**Comment by jaredkerim** [comment] 2016-08-30 15:34
Closing as a duplicate of #747

**Closed by jaredkerim** 2016-08-30 15:34 UTC
Labels: P3
