### ISSUE TITLE
Portrait images are cropped incorrectly

### ISSUE THREAD

**Issue by nchapman** [mozilla/activity-stream#3739] opened 2017-10-19 16:40 UTC
Here is an example of the "Recommended by Pocket" row with a portrait image in the third position. I imagine this applies to Highlights as well but it could be specific to this type:

<img width="779" alt="image" src="https://user-images.githubusercontent.com/3095/31782083-cf33a36c-b4ae-11e7-8a08-e25d25701b12.png">

That third image is this one:

<img src="https://img-getpocket.cdn.mozilla.net/direct?url=https%3A%2F%2Fstatic01.nyt.com%2Fimages%2F2017%2F10%2F16%2Ft-magazine%2Fnicki-minaj-slide-O7D6%2Fnicki-minaj-slide-O7D6-articleLarge.jpg&resize=w200">

We should try to show the person's face instead of their torso. I've had good luck with aligning portrait images to the top instead of middle. This requires that we know the dimensions of images ahead of time. There are fancier solutions (face detection 😁), but I think combining width to height ratio with alignment should get us pretty far.

**Comment by Mardak** [comment] 2017-10-19 17:39
Dupe of #3074

**Closed** 2017-10-19 17:39 UTC
