### ISSUE TITLE
Create an "activity-stream-newtab" source for Search Telemetry

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#2729] opened 2017-06-16 15:02 UTC
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1381460
When we switched over our search component to recycle the existing one in about:newtab and about:home (https://github.com/mozilla/activity-stream/blob/master/system-addon/content-src/components/Search/Search.jsx#L26-L32)  we see that we pass in "newtab" as the HealthReportKey. We did this in order to fix a failing test where we were originally passing in "activity" as a source, which wasn't recognized in BrowserUsageTelemetry.jsm as a valid source, and therefore we never added the appropriate Telemetry Probe, and failed some tests. The concern @dmose and I had was that by re-using the "newtab" source, we essentially mix up the data for searches that come in from tiles newtab with activity stream's newtab, since their sources are the same. At the time, @dmose and I weren't sure about how much engineering effort it would take to create a new source, so we decided to leave it as "newtab" for now.

After chatting with the folks in #fx-metrics on slack about this, we were told we probably need to add our own "activity-stream-newtab" source, since we definitely want to separate out the experience of activity stream vs current newtab. Georg Fritzsche is the guy we want to ask about what kind of engineering work is involved for adding a new source. At a minimum, we guess we have to add it to this list: https://dxr.mozilla.org/mozilla-central/source/browser/modules/BrowserUsageTelemetry.jsm#42, and possibly handle it differently here: https://dxr.mozilla.org/mozilla-central/source/browser/modules/BrowserUsageTelemetry.jsm#444, but we should ask Georg about what other work needs to be done to add it properly.

So, does this block preff-ing on in 56 for some users? Quoted by David Zeber on slack:

> dzeber [4:55 PM] :
> i’d recommend using the new source string prior to preffing on
> that said, it’s not a huge issue for nightly
> i’m not sure of how the engineering effort balances out on this
> but if it’s only the strings that need to be changed/added to whitelists, it’s probably best
> i would also claim that the scalars/events are lower priority (not sure if we’re using this data regularly at the moment)
> so they could potentially wait until beta/release

cc @Mardak @emtwo @k88hudson

**Comment by emtwo** [comment] 2017-06-16 15:55
Yea I would agree with dzeber that we probably don't want to mess with search telemetry for new tab since it could affect analysis being done on that.

On the other hand, do we need UT telemetry for Activity Stream search at all? If it's any easier to just not send UT for AS search perhaps that could be better since we are collecting collecting metrics via onyx

**Comment by sarracini** [comment] 2017-06-16 17:36
In that case (which is actually probably preferable) we could just add the source in BrowserUsageTelemetry so it gets picked up and then literally just do nothing when we get that action

**Comment by dmose** [comment] 2017-06-16 17:38
It seems like we'd have to talk to the metrics folks before turning off that data flow -- I suspect they're comparing search sources across a whole variety of things, and they probably want to continue to do that even after tiles goes away.

**Comment by piatra** [comment] 2017-07-17 12:08
There is now a [bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1381460) for this in order to get more info from people. I'm sure there will be a discussion around this.

**Comment by Mardak** [comment] 2017-07-26 18:01
This will need to handle 
Backport Bug 1381460 - Add telemetry search event for Activity Stream. f=florian, r=Dexter, data-r=bsmedberg #2954
https://bugzilla.mozilla.org/show_bug.cgi?id=1381460
https://hg.mozilla.org/integration/mozilla-inbound/rev/839d8a60a2ea

**Comment by Mardak** [comment] 2017-08-31 18:43
Is this actually necessary? Could healthreport just get whether activity stream is enabled and split on that? Seems like we've had some trouble landing this new healthreportkey, so I'm not sure if we'll also run into similar issues with about:home #3320.

@piatra what else is remaining to get this done?

**Comment by piatra** [comment] 2017-08-31 19:28
These seem to be all the bugs related to tests 

- [ ] https://github.com/mozilla/activity-stream/issues/3305
- [ ] https://github.com/mozilla/activity-stream/issues/3302
- [ ] https://github.com/mozilla/activity-stream/issues/3321
- [ ] https://github.com/mozilla/activity-stream/issues/3304
- [ ] https://github.com/mozilla/activity-stream/issues/3303

Here is the try run with AS on about:home

https://treeherder.mozilla.org/#/jobs?repo=try&revision=4e323761c128b40621ffdff46c0e92dc6463df34&group_state=expanded&selectedJob=127119493

@Mardak regarding healthreportkey I could look into it and find out if we can do that. Sounds likely. The current bug to add the "activity-stream" telemetry event is failing on linux64/debug I'm looking into getting a debug build on my machine and investigate.

**Comment by Mardak** [comment] 2017-08-31 23:55
I've made sure those listed issues are in the about:home column of the 57 project: https://github.com/mozilla/activity-stream/projects/16

**Comment by Mardak** [comment] 2017-09-14 19:43
@piatra what's the status of this? The bug and issue haven't been updated for more than a week

**Comment by Mardak** [comment] 2017-09-14 21:05
@tspurway maybe were you supposed to double check if we needed to change the health report key?

**Comment by piatra** [comment] 2017-09-14 21:07
Pushed to try again today to see if prerendering helps the intermittent tests but it does not.
The issue doesn't have to do with the search input element being ready but with the actual search provider. Next step is to debug this on a reference machine, it does not reproduce on fast hardware even if the platform is the same.

**Comment by Mardak** [comment] 2017-09-14 22:26
Well, if it's passing most everywhere else, it might make sense to split out the test to its own file and skip-if = problematic cases

**Comment by piatra** [comment] 2017-09-18 12:29
I split the test by moving the Activity Stream search test in a separate file. I set it to skip for `linux platform && debug`.

There is still a problem where the previously existing test (for newtab) now fails. Previously Activity Stream provided the "old newtab" healthreportkey, and the test passed. Now we have to turn Activity Stream off to go back to the "old newtab" and run the test. That's where it fails. Is it ok to move this test as well to the ignored file?

[Try run](https://treeherder.mozilla.org/#/jobs?repo=try&revision=fafb784bc60db621b30cc6a2b431dcc6db58f3c9&selectedJob=131704829) everything looks good except for the problem described above.

**Comment by Mardak** [comment] 2017-09-18 20:39
I would think we want to make sure tiles about:newtab is sending the correct telemetry. I wonder if it's just an issue with the preloaded browser. Can you figure out what scalar is being set? If it's the activity stream one, then the wrong page got loaded for the test.

**Comment by Mardak** [comment] 2017-09-18 20:42
> +skip-if = (os == 'linux' && debug)
nit: the parens aren't needed. And just making sure, this is failing intermittently on both linux32 and linux64? Otherwise you can specify `bits == 32`, etc. Also, generally good practice to include `# bug 1381460` comment for anyone tracking down the source of skipping.

**Comment by piatra** [comment] 2017-09-19 17:39
@Mardak [Logging the scalars](https://treeherder.mozilla.org/logviewer.html#?job_id=131971418&repo=try&lineNumber=7332) recorded returns `{}`.
I've tried to avoid that exact problem (preloaded browser) by [closing the first tab created and opening a new one](https://hg.mozilla.org/try/file/e45d09b2296ab9eb002f8d404e5c079c79866ce2/browser/modules/test/browser/browser_UsageTelemetry_content_activitystream.js#l54).

**Comment by piatra** [comment] 2017-09-25 18:00
I've had a new idea for this where I would [disable preloading in the test setup](https://hg.mozilla.org/try/rev/952e169330b1963ca81c949a2b1483d145cfb2e4) so that we don't have to close the tab to open a new one to ensure we don't get a preloaded Activity Stream tab.
Unfortunately that still [did not work](https://treeherder.mozilla.org/#/jobs?repo=try&revision=8d797ff59bd5fce3e54fed97bee7dc4990c65304&selectedJob=133112028) with 1 test failure on Linux debug (out of 5).
Now I'm disabling Activity Stream in the test setup phase and restoring the tests to what they were originally doing and see how that works out https://treeherder.mozilla.org/#/jobs?repo=try&revision=8985169ff8481ce101318a1b52e9a1a9ea308fa7.

**Closed** 2017-11-27 19:29 UTC
Labels: Bugzilla, fx59, Has PR, P1, Reporting

**Comment by Mardak** [comment] 2017-11-27 19:38
I'm assuming this was closed because this is no longer desired?
