### ISSUE TITLE
Persist the page's meta data

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#863] opened 2016-06-20 14:33 UTC
This is the meta bug for tracking the persistence of page's meta data, which is currently generated by embedly. The plan is to use a separate SQLite db as the data store, and to provide various "join" queries against the "Places" database.

**Comment by jaredkerim** [comment] 2016-06-20 18:55
This is a duplicate of #770, however this can now be considered the canonical tracking ticket for this effort and we will close #770.

**Comment by ncloudioj** [comment] 2016-06-20 20:16
Thanks @jaredkerim! Let's use this one to track the design and implementation of #770

**Comment by k88hudson** [comment] 2016-06-28 15:30
These are all the fields we currently use in our UI:

- url (provided by places)
- title (provided by places)
- description (provided by embedly)
- favicon url (provided by embedly, falls back to placesDB)
- favicon color as RGB (we compute this locally using the favicon in placesDB) 
- image url (from embedly)
- video/media url (from embedly)

**Comment by k88hudson** [comment] 2016-06-29 18:32
cc @jaredkerim @sarracini

**Comment by pdehaan** [comment] 2016-06-29 18:43
Is this related to https://github.com/mozilla/loci in any way?

Should we be capturing the page's full text from Fathom?

Also, should we include some TTL in each record so we can rescrape pages every X days (similar to Embedly's `cache_age`)?

> `cache_age` &mdash; How long Embedly is going to `cache` the response for? Generally, this is for a day, unless some external factor tells us to reevaluate the resource.
> 
> &mdash; via http://docs.embed.ly/docs/extract ([example](http://embed.ly/docs/explore/extract?url=http%3A%2F%2Ftechcrunch.com%2F2013%2F03%2F26%2Fembedly-now-goes-beyond-embedding-with-new-products-extract-display-for-making-sense-of-links-resizing-images%2F))

**Comment by ncloudioj** [comment] 2016-06-29 20:12
These are all the fields we currently use in our UI, plus the feedback from @jaredkerim @sarracini :

- url (provided by places)
- title (provided by places)
- type (provided by embedly)
- description (provided by embedly)
- favicon url (provided by embedly, falls back to placesDB)
- favicon color as RGB (we compute this locally using the favicon in placesDB) 
- image url (from embedly)
- video/media url (from embedly)
- canonical url (provider_url from embedly)
- cache_key url (generated by the addon) 
- expire_at (a timestamp)

**Comment by pdehaan** [comment] 2016-06-29 20:18
@k88hudson Do we also use [`provider_name`:mag:](https://github.com/mozilla/activity-stream/search?utf8=%E2%9C%93&q=provider_name&type=Code)  and [`provider_display`:mag:](https://github.com/mozilla/activity-stream/search?utf8=%E2%9C%93&q=provider_display&type=Code) from embedly?

**Comment by jaredkerim** [comment] 2016-06-29 20:21
@pdehaan this does not encompass full text storage/search.  loci will be related to this, but is outside the scope of this specific ticket.  This ticket just encompasses the creation of a sqlite database specifically for persisting metadata which may come from various sources (embedly, fathom, etc) and will replace the simplestorage based metadata persistence in place now.

With regards to specific schemas, we will have two tables with each of the following schemas I believe: 

# Metadata Table

field | type | description
--- | --- | --- 
id | Int | auto incrementing primary key
cache_key | String (Unique) | A simplified URL which is shared across multiple places URLs (ie protocol removed, query string reduced/removed)
canonical_url | String | The URL which the parser finds inside the DOM of a page 
type | String | the og:type tag ie 'article', 'video', 'page', etc
description | String | The meta description of the page
created_date | datetime | The date and time that this metadata row was inserted/created
expiry_date | datetime| The date and time this metadata row will expire

# Images Table

field | type | description
--- | --- | ---
id | Int | auto incrementing primary key
type | Int | The type of the image, initial types are: favicon 1, rich_icon 2, preview 3 (constants)
url | String | The URL for the image
height | Int | The height of the image in pixels
width | Int | The width of the image in pixels
color | String | The dominant/aggregate color of the image

# MetadataImage Join Table

field | type | description
--- | --- | --- 
metadata_id | Int | A foreign key onto the Metadata table
image_id | Int | A foreign key onto the Images table

**Comment by jaredkerim** [comment] 2016-06-29 20:32
As an example, a single pages metadata might look like the following:

id | cache_key | canonical_url | type | description | created_date | expiry | date
--- | --- | --- | --- | --- | --- | --- | ---
1 | //www.cbc.ca/news/politics/obama-trudeau-pena-nieto-three-amigos-1.3657558 | http://www.cbc.ca/news/politics/obama-trudeau-pena-nieto-three-amigos-1.3657558 | article |

**Comment by ncloudioj** [comment] 2016-06-29 20:34
LGTM! @jaredkerim 

As a side note, for the time being, the current storage API still relies on the `moz_favicons` table in PlacesDB for the favicons. Will persist them (including other images) in the Images table once we finish up the Metadata table stuff.

**Closed** 2016-07-11 19:35 UTC
Labels: Add-on APIs, in progress, metadata, P1
