### ISSUE TITLE
Bug 1273139 - Default top sites can be duplicated if a specific page other than homepage is visited first 

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#703] opened 2016-05-16 13:56 UTC
via https://bugzilla.mozilla.org/show_bug.cgi?id=1273139
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.16

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.16) was previously installed on a clean profile.  

[Steps to reproduce]:
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Open a "New Tab" page.
3. Visit a default website specific page link other than the homepage that is already in "Top Sites" area (eg: any YouTube song / video).
4. Open another "New Tab" page and observe the "Top Sites" area.
 
  
[Expected results]:
The default YouTube top site was updated with the link of the visited song / video.
 
Actual results:
Two YouTube top sites are displayed, one with the default page link and one with the link from the visited song / video. 

[Notes]:
- This issue is reproducible for all the default Top Sites displayed.
- Attached a screenshot with the issue (https://goo.gl/K8f2mq).

**Comment by bryanbell** [comment] 2016-06-01 23:56
Top sites should be designed to favor top-level domains (homepages) over all sub-pages of a site whenever possible.

**Comment by oyiptong** [comment] 2016-06-27 18:10
jared will reference to the bug this is a duplicate of

**Comment by jaredkerim** [comment] 2016-06-27 18:11
Closing as a duplicate of #405

**Closed by jaredkerim** 2016-06-27 18:11 UTC
Labels: Bugzilla
