### ISSUE TITLE
Highlight results with no images look objectively weird

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#582] opened 2016-04-26 22:18 UTC
Found in 1.0.12

---

### Steps to reproduce:
1. Install the latest add-on.
2. Browse some stuff. Preferably stuff without preview images. I happened to be testing TestPilot experiments. (see http://embed.ly/docs/explore/extract?url=http%3A%2F%2Ftestpilot.dev.mozaws.net%2Fexperiments%2Factivity-stream)
3. Open New Tab or Timeline page.

### Actual results:
2 of the 3 of my Highlights results don't have background images (and randomly have white backgrounds, which makes everything look empty).

![activity_stream](https://cloud.githubusercontent.com/assets/557895/14836013/fa0eb5a0-0bc1-11e6-86e0-2dab4c4f22d0.png)

### Expected results:
Exclude Highlight results with no preview images?

**Comment by SoftVision-PaulOiegas** [comment] 2016-04-27 07:39
I think we discussed the same subject in #560 . Kate replied "This is the intended behaviour: image-less items will show up as a fallback if no items are available from the Highlights query.".

**Comment by jaredkerim** [comment] 2016-06-27 18:25
This will be resolved when we store metadata locally in #863 and are able to explicitly query for highlights with images.  Closing this.

**Closed by jaredkerim** 2016-06-27 18:25 UTC
