### ISSUE TITLE
Perma-orange: browser_410196_paste_into_tags.js leaked about:newtab

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2803] opened 2017-06-29 04:53 UTC
On debug builds running mochitest-clipboard:

```
LOG ERROR | TEST-UNEXPECTED-FAIL | browser/components/places/tests/browser/browser_410196_paste_into_tags.js | leaked 1 window(s) until shutdown [url = about:newtab]
```
linux: https://treeherder.mozilla.org/logviewer.html#?job_id=110251070&repo=pine&lineNumber=7090
linux64: https://treeherder.mozilla.org/logviewer.html#?job_id=110241877&repo=pine&lineNumber=4796
mac: https://treeherder.mozilla.org/logviewer.html#?job_id=110236046&repo=pine&lineNumber=5217
win64: https://treeherder.mozilla.org/logviewer.html#?job_id=110249799&repo=pine&lineNumber=5855

**Comment by Mardak** [comment] 2017-06-29 05:32
Seems like these are related:

```
 LOG ERROR | TEST-UNEXPECTED-FAIL | browser/components/places/tests/browser/browser_0_library_left_pane_migration.js | leaked 1 window(s) until shutdown [url = about:newtab] [log…] 
 LOG ERROR | TEST-UNEXPECTED-FAIL | browser/components/places/tests/browser/browser_423515.js | leaked 1 window(s) until shutdown [url = about:newtab] [log…] 
```
https://treeherder.mozilla.org/logviewer.html#?job_id=110645859&repo=try&lineNumber=5328
https://treeherder.mozilla.org/logviewer.html#?job_id=110645859&repo=try&lineNumber=5330

**Comment by k88hudson** [comment] 2017-06-29 22:38
I'm unable to reproduce this locally unfortunately

**Comment by Mardak** [comment] 2017-06-30 04:39
@dmose The leaks started with the URI_MUST_LOAD_IN_CHILD change https://bugzilla.mozilla.org/show_bug.cgi?id=1365643

I built locally only removing the flag and leaving all the logic (just in case some of the added logic caused the leak), and the leaks went away. I tested using `./mach mochitest browser_as_load_location.js --repeat=2` and here's a diff from a no-leak good run to a bad leaky run (with various numbers replaced):
https://github.com/Mardak/activity-stream/compare/3d750e1...9f8303e

In general there are more `DOMWINDOW`s being `++`created and `--`destroyed but they seem to all be destroyed before `Completed ShutdownLeaks collections in process PRNT` but I'm not entirely sure what is being compared.

In particular `[pid = CHD3] [serial = 6]` had loaded about:newtab and is one of the leaking windows. It was created in the second run of the test, but before the second test even ran, there's a `Completed ShutdownLeaks collections in process CHD3`. After the second test finishes, there is a `--DOMWINDOW == 2 [pid = CHD3] [serial = 6] [url = about:newtab]` followed by `Completed ShutdownLeaks collections in process PRNT`.

**Comment by Mardak** [comment] 2017-06-30 18:48
I tried adding a `await new Promise(resolve => setTimeout(resolve, 10000));` at the end of `browser_as_load_location.js` to see if the tab closing just needed more time, and it's still leaking. It's also leaking if newtab.preload is off and the above waiting.

**Comment by sarracini** [comment] 2017-07-07 17:33
This doesn't look like this is happening anymore, however we have another similar test failure. I'll close this an open a new bug and link back to this one

**Closed by sarracini** 2017-07-07 17:33 UTC
Labels: Fx / Pref on in Nightly, MVP, P1, Tests

**Comment by Mardak** [comment] 2017-07-07 20:22
#2829 is the new issue. I'll try to see if anything in particular fixed this test that we can apply to that other issue.
