### ISSUE TITLE
Set about:home to activity-stream

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#2598] opened 2017-05-15 17:23 UTC
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1392324

**Comment by Mardak** [comment] 2017-08-08 19:08
Unclear what the plan is here. One potential approach is to have aboutRedirector point to activity-stream's html resource when it's enabled?

**Comment by piatra** [comment] 2017-08-21 16:45
The current plan right now is to just enable Activity Stream on about:home regardless of any pref, run all the tests and see the workload required for this change.

**Comment by piatra** [comment] 2017-08-21 18:02
Result of setting AS to about:home right now.
<img width="1282" alt="screen shot 2017-08-21 at 20 00 44" src="https://user-images.githubusercontent.com/810040/29532077-affe7796-86ab-11e7-9c18-f19e06ba19e1.png">

**Comment by Mardak** [comment] 2017-08-21 18:06
I believe @sarracini and @AdamHillier already did some investigation leading to https://bugzilla.mozilla.org/show_bug.cgi?id=1390282

**Comment by sarracini** [comment] 2017-08-21 18:52
@AdamHillier's patch should fix that - are you on the latest nightly?

**Comment by Mardak** [comment] 2017-08-21 18:57
Which patch are you referring to? `AboutNewTab` currently only registers "about:newtab" https://searchfox.org/mozilla-central/source/browser/modules/AboutNewTab.jsm#33

**Comment by sarracini** [comment] 2017-08-21 19:09
ooooh I thought the patch Adam landed also registered about:home. My bad

**Comment by Mardak** [comment] 2017-08-21 21:11
This needs to at least be behind a pref so about:home activity stream can be disabled separate from about:newtab activity stream.

**Comment by sarracini** [comment] 2017-08-21 21:12
Also involves generalizing aboutnewtabservice.js to be able to watch for different pref changes

**Comment by AdamHillier** [comment] 2017-08-21 21:15
@piatra My patch just allowed you to register multiple pages. Didn't start registering about:home as wanted to wait until it was actually needed. But yeah, that should fix it.

**Comment by Mardak** [comment] 2017-08-21 22:33
Instead of modifying `aboutNewTabService.js` potentially we can just have `AboutRedirector.cpp` check a pref. I would suggest the pref be something like `browser.newtabpage.activity-stream.disableHome` which better implies that it's an exception from activity stream being enabled as opposed to about:home being able to separately enable from about:newtab.

Here's an example of the activity stream pref being read/updated from `AboutRedirector`:
https://searchfox.org/mozilla-central/source/browser/components/about/AboutRedirector.cpp#204-209

**Comment by piatra** [comment] 2017-08-23 16:53
Try run with Activity Stream on about:home 
https://treeherder.mozilla.org/#/jobs?repo=try&revision=0cb966566398df33bde096c2a7a75287c3e5c8aa&selectedJob=125153766

**Comment by Mardak** [comment] 2017-08-23 17:01
Looking at that first test failure:
```
 FAIL | browser/components/migration/tests/browser/browser_undo_notification.js | Test timed out [log…] 
```
https://treeherder.mozilla.org/logviewer.html#?job_id=125153766&repo=try&lineNumber=4472

It just passed with "[task 2017-08-23T12:31:04.526335Z] 12:31:04     INFO - TEST-PASS | browser/components/migration/tests/browser/browser_undo_notification.js | Should have opened a tab with a survey - "

So looks like the test passed the first set of checks for about:newtab and is failing for about:home:
https://searchfox.org/mozilla-central/source/browser/components/migration/tests/browser/browser_undo_notification.js#31-38

**Comment by piatra** [comment] 2017-08-24 09:23
Talos run finished. It's only 1 run so results aren't confident but it doesn't look like we're making a negative perf impact. https://treeherder.mozilla.org/perf.html#/compare?originalProject=mozilla-central&newProject=try&newRevision=85cc50fb1bcf81c5c91a204cee93441bd2b7ffce&framework=1&showOnlyImportant=0&selectedTimeRange=172800

**Comment by Mardak** [comment] 2017-08-24 17:11
You can retrigger the talos runs to get more accurate performance numbers. Probably shouldn't trust anything with fewer than 6 runs unless it's a really large change. I've gone ahead and retriggered them. Also, the talos runs are only on mac, and performance can be quite different on other platforms.

**Comment by Mardak** [comment] 2017-08-25 10:22
Looks like maybe a 3% sessionrestore regression?

**Comment by Mardak** [comment] 2017-08-25 10:30
https://hg.mozilla.org/mozilla-central/rev/0ae745e100aa

There needs to be a backport of the MessageChannel change. And various followup issues filed for fixing which test failures and turning the pref.

**Comment by Mardak** [comment] 2017-08-25 18:00
So with #3236 separately filed. I suppose this issue will be for actually turning on activity stream on about:home.

**Comment by sarracini** [comment] 2017-09-13 17:17
Closing this since the associated bug has landed - the work to actually flip the pref on will be done in mc and will need another bug for it

**Closed by sarracini** 2017-09-13 17:17 UTC
Labels: Bugzilla, fx57, P1

**Comment by Mardak** [comment] 2017-09-14 11:23
Turned on here: https://hg.mozilla.org/mozilla-central/rev/3ce5a9419d5b
