### ISSUE TITLE
Context menu should allow you to Remove Bookmark from Bookmarked items

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#1937] opened 2017-01-09 21:41 UTC
![screen shot 2017-01-09 at 3 39 41 pm](https://cloud.githubusercontent.com/assets/139451/21784602/eee14b4e-d681-11e6-829e-afe9cb3776cb.png)

I cannot remove a bookmark from an item using the context menu on New Tab. What's more, when I click "Bookmark" it adds a second entry in Library for the item (below):

![screen shot 2017-01-09 at 3 36 23 pm](https://cloud.githubusercontent.com/assets/139451/21784634/10e97018-d682-11e6-8aa7-1bfe3cdf7cc9.png)

**Comment by sarracini** [comment] 2017-01-13 20:48
Dupe of #1957. Closing this as PR #1959 will fix this :)

**Closed by sarracini** 2017-01-13 20:48 UTC
