### ISSUE TITLE
Bug 1290465 - Another "Top Sites" context menu can no longer be opened if a previous "Top Sites" context menu was previously opened

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#1000] opened 2016-07-29 14:45 UTC
via https://bugzilla.mozilla.org/show_bug.cgi?id=1290465
<br>
[Affected versions]:
- Firefox 45 and up
- Activity Stream 1.1.1-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on (v1.1.1-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Click on "+" button to open a new tab.
3. Click the "..." button on any item from "Top Sites".
4. After the context menu is displayed, click the "..." button for a another site from "Top Sites"

[Expected result]:
- The context menu for the currently selected site is displayed.

[Actual result]:
- The context menu is not displayed for the currently selected site or any other site selected from "Top Sites".

[Notes]:
- If you click somewhere else on the page before and after on the "..." button, the context menu will be correctly displayed.
- A screen recording describing the issue was attached https://bugzilla.mozilla.org/attachment.cgi?id=8775987

**Comment by oyiptong** [comment] 2016-08-02 17:17
might be a duplicate of an issue @k88hudson is already aware of

**Comment by aaronrbenson** [comment] 2016-10-27 17:28
On a fresh profile, I'm still seeing this issue.

![screen recording 2016-10-27 at 12 25 pm](https://cloud.githubusercontent.com/assets/139451/19778094/cdb3ee20-9c40-11e6-9fbe-d0c62d07d77c.gif)

**Comment by sarracini** [comment] 2016-11-09 17:56
This was fixed with #1748

**Closed by sarracini** 2016-11-09 17:56 UTC
Labels: Bugzilla, P2
