### ISSUE TITLE
After bookmarking a site with a video preview, the line connecting the items is too short (Bug 1279482)

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#834] opened 2016-06-10 12:14 UTC
via https://bugzilla.mozilla.org/show_bug.cgi?id=1279482
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.19-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.19-dev) was previously installed on a clean profile.
- Have enough history so that the "Top Sites", "Highlights", "History" areas are populated with visited websites.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Bookmark a video.
3. Click the Activity Stream button from the browser toolbar and go to the bookmarks page.
4. Observe the newly bookmarked video.

[Expected result]:
The line connecting the bookmarked items is correctly rendered.

[Actual result]:
After bookmarking a video the line connecting items is not properly rendered in the Bookmarks page.

[Notes]:
- If you bookmark a video within the 10 minute timeframe, the line is correctly rendered. However, if you bookmark an item after the 10 minute timeframe, half a line is displayed.
- Attached a screenshot of the issue.
![connection line is not hidden](https://cloud.githubusercontent.com/assets/17258026/15963896/0e35ae56-2f1e-11e6-97ad-4948ffc946c5.png)

**Comment by oyiptong** [comment] 2016-06-27 17:19
duplicate of #880

**Comment by sarracini** [comment] 2016-10-17 18:39
Closing this since we've removed timeline and recent activity

**Closed by sarracini** 2016-10-17 18:39 UTC
Labels: Bug, Bugzilla, Good first bug, P2
