### ISSUE TITLE
Videos in the timeline that are not connected to previous history should not have a timeline strand

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#880] opened 2016-06-23 22:47 UTC
![screen shot 2016-06-23 at 5 37 05 pm](https://cloud.githubusercontent.com/assets/139451/16322472/d3f16a14-3968-11e6-8294-d4c18701c022.png)

Pretty descriptive title. The image should make it crystal clear.

**Comment by SoftVision-VladBacia** [comment] 2016-06-24 08:22
@aaronrbenson , this issue is related to #834.

**Comment by oyiptong** [comment] 2016-06-27 17:20
closing as duplicate of #834

**Closed by oyiptong** 2016-06-27 17:20 UTC
Labels: P2
