### ISSUE TITLE
First Time Opening

### ISSUE THREAD

**Issue by miken700** [mozilla/activity-stream#1477] opened 2016-10-07 13:45 UTC
Spins forever on the first page with "Hang on tight! We are analyzing your history to personalize your experience". I've tried it on Linux Mac and Windows with the same results. Guessing it's something to do with my history...?

**Comment by jaredkerim** [comment] 2016-10-11 17:41
@miken700 Thanks for reporting this, we will investigate this issue.  If you're able to reproduce this again, can you go to Tools -> Developer -> Browser Console and copy all the messages you see in there into this ticket so we can debug this more thoroughly? Thanks!

**Comment by miken700** [comment] 2016-10-14 13:02
@jaredkerim ,

Browser Console messages:
`
Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.(unknown)
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src resource://activity-streams”).activity-streams.html:1

`

**Comment by sarracini** [comment] 2017-01-17 21:50
Closing this as we can't reproduce - will re-open if the issue occurs again

**Comment by miken700** [comment] 2017-01-17 23:45
Just repro'd it. Error is in bundle.js:4182, "TypeError: arguments is not iterable".

> mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create vendor.bundle.js:17:3220
> 
> TypeError: arguments is not iterable
> defineActions/</composed()
>  bundle.js:4182
> componentDidMount()
>  bundle.js:5790
> .notifyAll()
>  vendor.bundle.js:16
> f.close()
>  vendor.bundle.js:18
> o<.closeAll()
>  vendor.bundle.js:1
> o<.perform()
>  vendor.bundle.js:1
> u()
>  vendor.bundle.js:16
> o<.perform()
>  vendor.bundle.js:1
> d.batchedUpdates()
>  vendor.bundle.js:18
> i()
>  vendor.bundle.js:1
> j._renderNewRootComponent()
>  vendor.bundle.js:16
> j._renderSubtreeIntoContainer()
>  vendor.bundle.js:16
> j.render()
>  vendor.bundle.js:16
> renderRootWhenAddonIsReady()
>  bundle.js:44
> <anonymous>
>  bundle.js:51
> t()
>  vendor.bundle.js:1
> window.webpackJsonp()
>  vendor.bundle.js:1
> <anonymous>
>  bundle.js:1
>  bundle.js:4182:67
> 
> Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src resource://activity-streams"). activity-streams.html:1:0



it's on the return line with `...argument` below in case the line numbers are different,
`
	  defineActions(definitions) {
	    var _this = this;

	    Object.keys(definitions).forEach(name => {
	      const definition = definitions[name];
	      const composed = function () {
	        return compose([..._this.validators, definition], _this)(...arguments);
	      };
	      composed.definition = definition;
	      this.actions[name] = composed;
	    });
	  }`

**Comment by dveditz** [comment] 2017-01-19 00:12
I'm getting the same symptoms, but not a CSP error. Here's the Browser Console log:

16:06:33.367 Error: When not using *.example.org wildcard, the string supplied is expected to be either an exact URL to match or a URL prefix. The provided string ('firefoxux.github.io') is unlikely to match any pages.  match-pattern.js:46:15
16:06:33.499 SyntaxError: test for equality (==) mistyped as assignment (=)?  bundle.js:648:43
16:06:33.505 ReferenceError: reference to undefined property "$$typeof"  vendor.bundle.js:1:6437
16:06:33.505 ReferenceError: reference to undefined property "autobind"  vendor.bundle.js:16:9465
16:06:33.505 ReferenceError: reference to undefined property "Buffer"  bundle.js:3866:45
16:06:33.505 ReferenceError: reference to undefined property "checked"  vendor.bundle.js:2:4329
16:06:33.505 ReferenceError: reference to undefined property "top_sites_hint"  bundle.js:1243:48
16:06:33.596 POST 
XHR 
https://tiles.services.mozilla.com/v3/links/activity-stream [HTTP/1.1 200 OK 111ms]
16:06:33.659 &lt;unavailable&gt;  timers.js:43
16:06:33.689 ReferenceError: reference to undefined property "innerID"[Learn More]  webconsole-utils.js:31:9
16:06:34.460 ReferenceError: reference to undefined property "componentDidUpdate"  vendor.bundle.js:17:28039
16:06:34.460 ReferenceError: reference to undefined property "broadcast"  bundle.js:4302:1

**Comment by jaredkerim** [comment] 2017-01-19 18:27
I've seen this issue reproduced with the current dev build on master so we will look at and address this!

**Comment by dmose** [comment] 2017-01-23 16:56
For the "arguments is not iterable" case, perhaps we need to be using the arguments[@@iterator] syntax: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments#Properties

**Comment by jaredkerim** [comment] 2017-01-25 18:16
Closing this is a duplicate of #1995

**Closed by jaredkerim** 2017-01-25 18:16 UTC
Labels: Bug, MVP, P2
