### ISSUE TITLE
Bug 1271245 - Revisiting the same website will not add it to "Highlights" section after 30 minutes

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#663] opened 2016-05-09 12:01 UTC
via https://bugzilla.mozilla.org/show_bug.cgi?id=1271245
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.15

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

Prerequisites]:
- Latest Activity Stream add-on version (1.0.15) was previously installed on a clean profile.  

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Visit some websites that would appear in "Highlights" section. (eg. 9gag.com)
3. Click the Activity Stream button from the browser toolbar.
4. Observe the "Highlights" tiles from the Timeline page.
5. Revisit the website from step #2 after 25 minutes.

[Expected result]:
- If the visited website meets all the requirements for "Highlights", then it should be added to "Highlights" after 30 minutes. 

[Actual result]:
- If you revisit the website at every 25 minutes then "Highlights" tiles will never be populated with the content from the visited website. 

[Notes]:
- In the current behavior, if 30 minutes have passed since last visit, the website is not displayed in "Highlights". It will be displayed only if you visit another website.
- In my opinion, for a better users experience the "Highlights" tiles should be updated instantly because the content displayed is related to History.
- The issue is reproducible on the New Tab page as well.
- Attached screen recording with the issue https://goo.gl/nh9eK8 .

**Comment by rlr** [comment] 2016-05-18 20:15
This is working as currently designed. URLs visited in the past 30 minutes are not shown in highlights.

Do we want to change this behavior? @nchapman @oyiptong 

If not, we can close this out.

**Comment by SoftVision-PaulOiegas** [comment] 2016-05-19 08:46
I think you misunderstood the issue. There are 3 cases in the current implementation:
1. If you visit just one single web page once, it will never be displayed in the "Highlights" section until you visit a different one, even if 30 minutes have passed. 
2. If you visit a single web page for multiple times for the whole day, the page won't be displayed in the "Highlights" section. 
 3. If you visit multiple web pages, the last visited web page will not be displayed in "Highlights" section after 30 minutes if the same one is visited after the interval.

**Comment by rlr** [comment] 2016-05-19 15:55
@SoftVision-PaulOiegas Ah, thanks for clarifying. Regrabbing to look into it further.

**Comment by rlr** [comment] 2016-05-19 19:30
I was able to repro and found the issue. The problem is we cache (via `Memoizer`) places DB queries and don't ever invalidate/dump the cache until a change happens in the places DB (user visits a new URL, for example). It seems like we are going to have to invalidate the cache every 30 minutes. It's possible that it only has to be done for the highlights query since it is time sensitive.

**Comment by rlr** [comment] 2016-05-25 13:07
fixed via pull #742

**Closed by rlr** 2016-05-25 13:07 UTC
Labels: Bug
