### ISSUE TITLE
Context menu doesn't reflow very well on narrow browsers

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#831] opened 2016-06-10 00:44 UTC
Amid all my screenshots and tomfoolery, I notice that if my browser isn't very wide (or maybe I'm on a Macbook Air), that my context menu disappears off the right hand side of the browser. Not sure if we want to go down the path of trying to calculating available width and opening the context menu over the activity stream item if the browser width is less than < 800px (or whatever arbitrary number).

Or maybe this is a simple media query CSS fix and is No Big Deal(tm).

<img width="964" alt="new_tab_and_activity-stream_generate-html_js_at_be02057fb6a415c5395bcabfd26e3df1ea2acdb5_ _mozilla_activity-stream" src="https://cloud.githubusercontent.com/assets/557895/15951012/44c77176-2e69-11e6-83d2-8514564ed5fc.png">

**Comment by oyiptong** [comment] 2016-06-27 17:22
duplicate of #835

**Closed by oyiptong** 2016-06-27 17:22 UTC
