### ISSUE TITLE
Bug 1273164 - The search bar from New Tab page is no longer working on latest Nightly versions

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#706] opened 2016-05-16 15:06 UTC
via https://bugzilla.mozilla.org/show_bug.cgi?id=1273164
<hr>
[Affected versions]:
- Nightly 49.0a1
- Activity Stream 1.0.16

[Affected Platforms]:
- All Windows
- All Linux
- All Mac OS

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.16) was previously installed on a clean profile.  

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Open a new tab.
3. Write something in the search field.
4. Click the blue "right arrow" button or press "Enter" key.

[Expected result]:
- A search is performed with the default Search Engine for the written string.

[Actual result]:
- The search is not performed.

[Regression range]:
Due to the fact that the search field worked on previous Nightly builds, I have used the mozregression tool to find the regression window. Here is the pushlog URL: https://goo.gl/k6LHB5 . It seams that the search bar functionality broke after Bug 1210410 was fixed. 

[Notes]:
- On the latest Firefox release and latest Beta the search bar works properly. 
- Is reproducible only on Nightly and Aurora.

**Comment by sarracini** [comment] 2016-05-16 15:21
Notes:
 * this is happening because ContentSearch.jsm went through a refactoring and landed in nightly, so SearchProvider.js needs to be adjusted accordingly
 * as Olivier mentioned in #704 it needs to be backwards compatible with the old, pre-refactored version of ContentSearch.jsm

**Comment by sarracini** [comment] 2016-05-24 15:15
fixed with #736

**Closed by sarracini** 2016-05-24 15:15 UTC
Labels: Add-on APIs, Bug, Bugzilla, Critical, Search

**Comment by tspurway** [comment] 2016-05-25 17:15
@SoftVision-PaulOiegas @SoftVision-VladBacia could you guys take a look and verify this, we would like to make a production release of 1.0.18

**Comment by SoftVision-VladBacia** [comment] 2016-05-26 12:21
We have tested this on Win 7 x64, Win 8.1 x64, Win 10 x64, Ubuntu 15.10 x64, Mac OS 10.11 with latest Nightly 49.0a1 (Build ID: 20160525063710), latest Aurora 48.0a2 (Build ID: 20160526004016), latest Beta 47.0b8 (Build ID: 20160523113146), latest Release 46.0.1 (Build ID: 20160502172042) and the issue is no longer reproducible.
