### ISSUE TITLE
Bug 1280432 - Bookmarked websites from Highlights, are redisplayed after page refresh if they were previously deleted from history

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#858] opened 2016-06-17 08:23 UTC
via https://bugzilla.mozilla.org/show_bug.cgi?id=1280432

<hr>

[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.1.0

[Affected Platforms]:
- All Windows
- All Linux
- All Mac OS

[Prerequisites]:
- Latest Activity Stream add-on version (1.1.0) was previously installed on a profile.
- Have more history so that the "Highlights" area is populated with visited websites.
- Have at least one bookmarked website in "Highlights".

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the Activity Stream button from the browser toolbar.
3. Hover the bookmarked website from "Highlights" tile.
4. Click on "..." context menu button.
5. Click "Delete form History" option.
6. Refresh the page.

[Expected result]:
- The website is deleted from History and after page refresh, is no longer displayed in Highlights.

[Actual result]:
- The website is deleted from History, disappears from "Highlights", but after page refresh the website is redisplayed in "Highlights".

[Notes]:
- This issue is also reproducible on Activity Stream New Tab page.
- Attached a screen recording of the issue https://goo.gl/vpJyFt.

**Comment by sarracini** [comment] 2016-06-27 17:10
Ref: #859

**Comment by SoftVision-VladBacia** [comment] 2016-06-28 09:10
This issue could not be verified. It is blocked by #887 .

**Comment by k88hudson** [comment] 2016-07-19 22:38
I'm no longer seeing this issue on master. Also, this is a dupe of https://github.com/mozilla/activity-stream/issues/910

**Comment by SoftVision-VladBacia** [comment] 2016-07-20 10:33
This issue has been verified on Win 8.1 x64, Mac OS X 10.11 and Ubuntu 14.04 x64 with latest Nightly 50.0a1 (Build ID: 20160719030224) using latest Activity Stream v1.1.0-custom build and Activity Stream v1.1.0-dev-1468949420 and could reproduce it.

[Here](https://bugzilla.mozilla.org/attachment.cgi?id=8772792) is a video of the issue.

**Comment by k88hudson** [comment] 2016-07-20 19:01
Ok, I was able to reproduce! Thank you so much for the video

**Comment by k88hudson** [comment] 2016-07-21 15:54
Ok, this should now be fixed once 790d04b0a4db4ba2c9dce16069f0e697c7dc6f9d reaches the dev build. Could you confirm?

**Comment by SoftVision-VladBacia** [comment] 2016-07-22 08:25
This issue has been verified on Win 8.1 x64, Mac OS X 10.11 and Ubuntu 14.04 x64 with latest Nightly 50.0a1 (Build ID: 20160721030216) using latest Activity Stream v1.1.0-dev-1469146673 and and Activity Stream v1.1.0-dev-1468949420 and could reproduce it.

- After further investigations we observed that this issue is happening only for the bookmarked item that is displayed in the 1st tile form Highlights. 
- If bookmarked items are displayed in the 2nd or 3rd tile from Highlights and they are removed from History, the bookmarked items that were deleted will no longer be displayed in Highlights area after a page refresh.

**Comment by sarracini** [comment] 2017-01-17 22:20
I fixed this

**Closed by sarracini** 2017-01-17 22:20 UTC
Labels: Bug, P2

**Comment by Softvision-VladBacia** [comment] 2017-01-18 14:05
This issue is no longer reproducible in Activity Stream Dev 1.3.0-dev-1484695187.

**Comment by Softvision-VladBacia** [comment] 2017-01-18 14:10
This issue is no longer reproducible in Activity Stream Dev 1.3.0-dev-1484695187.
