### ISSUE TITLE
ACTION <unavailable> messages piling up in browser console

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#2141] opened 2017-02-07 21:41 UTC
We are seeing hundreds of these `ACTION <unavailable> redux-logger.js` messages pile up in the browser console and it may indicate that there is some kind of accidental additional events being fired in the main thread.

Steps to reproduce

1) On master branch, remove all experiments from experiments.json so it just says `{}`
2) Start activity stream on a profile with history: npm start firefox
3) about:addons -> disable activity stream
4) open browser console
5) about:addons -> enable activity stream
6) watch the browser console, I see:

![screenshot 2017-02-07 16 38 05](https://cloud.githubusercontent.com/assets/119884/22712845/46739522-ed54-11e6-802c-97effe32a24a.png)

**Comment by dmose** [comment] 2017-02-07 21:45
So, in theory, the way to see what the actions actually are is to go into about:addons, and from the gear menu, select "debug addons", and the click the debug button next to the installed version of activity stream.  That should get you a console that will actually print the right thing.

**Comment by rlr** [comment] 2017-02-07 21:48
@dmose is there anything special I need to do to enable these messages from `redux-logger`? I am not seeing them in my local setup.

My config.yml looks like:

```
DEVELOPMENT: true
LOGGING: true
USE_SHIM: false
```

**Comment by jaredkerim** [comment] 2017-02-07 22:03
@dmose my browser console shows:
![screenshot 2017-02-07 17 02 33](https://cloud.githubusercontent.com/assets/119884/22713615/3b51975e-ed57-11e6-9e74-9e8255ae6057.png)

but the addon debug console only shows:

![screenshot 2017-02-07 17 02 56](https://cloud.githubusercontent.com/assets/119884/22713629/48dd09e4-ed57-11e6-87e0-98e70198eb6e.png)

**Comment by rlr** [comment] 2017-02-07 22:10
nvm, i figured out the logging thing. I dont get the ACTION ones in the addon console either.

**Comment by dmose** [comment] 2017-02-07 22:15
@jaredkerim doh!  The next step might be to ask in #devtools.

**Comment by rlr** [comment] 2017-02-10 17:07
What I've learned so far is all these `redux-logger.js` messages come from the content side. If you open up the normal dev tools console, you'll see the action data for them:
<img width="1272" alt="screen shot 2017-02-10 at 12 03 48 pm" src="https://cloud.githubusercontent.com/assets/36629/22836100/1cfc8884-ef89-11e6-9e9f-fbfe7ced4033.png">

So that doesn't seem like a big deal. But if it gets into an infinite loop, then that's a bug in content that we should look at. I haven't been able to reproduce that.

Note that actions will pile up if you type into the search box since each keystroke generates an action on the content side.

**Comment by jaredkerim** [comment] 2017-02-15 18:54
We have difficulty reproducing this right now, bumping back to the next sprint to see if it pops up again.

**Comment by rlr** [comment] 2017-02-28 16:27
Closing for now. @jaredkerim, please reopen if you see again.

**Closed by rlr** 2017-02-28 16:27 UTC
Labels: Bug, MVP, P1
