### ISSUE TITLE
Add a function to remove a bookmark

### ISSUE THREAD

**Issue by oyiptong** [mozilla/activity-stream#670] opened 2016-05-10 17:51 UTC
Content needs an API to be able to remove a bookmark.

This will consist of creating a function in `PlacesProvider.js` that will make a call to `Bookmarks.jsm` to remove the said bookmark.

It will be similar to https://github.com/mozilla/activity-stream/blob/4d5c47a05a1caca0864b1b7342e700443d5b8333/lib/PlacesProvider.js#L275

But will make a call to https://dxr.mozilla.org/mozilla-central/source/toolkit/components/places/Bookmarks.jsm#385

Additionally, the bookmark API bindings need to be implemented in `lib/ActivityStreams.js` and in `common/action-manager.js` so that they are accessible to content.

**Comment by k88hudson** [comment] 2016-05-10 21:07
This is a duplicate of https://github.com/mozilla/activity-stream/issues/666 but I will leave this one open

**Closed** 2016-05-11 23:26 UTC
Labels: Add-on APIs, Add-on platform, Good first bug
