### ISSUE TITLE
Bug 1270762 - Missing incompatible notification in the UI, when installing Activity Stream from Test Pilot

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#656] opened 2016-05-06 08:12 UTC
via https://bugzilla.mozilla.org/show_bug.cgi?id=1270762
<hr>
[Affected versions]:
- Firefox 44.0 and down
- Activity Stream 1.0.15

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Test Pilot is installed on the Fx profile

[Steps to reproduce]:
1. Start Firefox browser with the profile where Test Pilot was previously installed.
2. Enable Activity Stream add-on from Test Pilot.

[Expected results]:
The user is notified that the add-on is not compatible with Fx versions lower than 45.0.

[Actual results]:
From the UI behavior the user understands that the add-on was successfully installed.
There is no notification that the add-on is incompatible with Fx version.

[Notes]:
Only in about:addons the user will be informed that the add-on is not compatible with the Fx version.

**Comment by rlr** [comment] 2016-05-10 19:21
I feel like this logic belongs in the Test Pilot site (AMO does this, for example).

What should we do on our end if we detect the user is on an older version of Firefox but installed the addon? @nchapman @bryanbell

**Comment by edmoz** [comment] 2016-06-23 20:44
dupe of https://github.com/mozilla/testpilot/issues/906

**Closed by edmoz** 2016-06-23 20:44 UTC
Labels: Bug, Bugzilla, Design feedback needed
