### ISSUE TITLE
Confirm we have all regions requried for 56 Shield Study localized

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#2774] opened 2017-06-27 21:08 UTC
We need to confirm which locales are important to be 100% localized for landing in 56 with product, and make sure we have the strings localized.

**Comment by flodolo** [comment] 2017-07-03 19:46
I'm still seeing several strings not available for translation (recent bookmarks, visit again sections). When are you planning to expose them for localization? I failed to spot any open issue for that.

**Comment by Mardak** [comment] 2017-07-03 21:04
There was a recent string addition a few days ago that will be in the mozilla-central version of the add-on soon: https://github.com/mozilla/activity-stream/pull/2812/files#diff-906742e1af7418eb557312dc9217f2f1

The "recent bookmarks" section is in the Test Pilot version, which is stopping development, and it's unclear how soon that will make it in to the mozilla-central version.

I can just export all of those (pin, recent, visit again, etc.) to get the strings localized sooner than later.

**Comment by flodolo** [comment] 2017-07-03 23:10
> I can just export all of those (pin, recent, visit again, etc.) to get the strings localized sooner than later.

That sounds like a good idea, unless we plan to add more in this cycle. Please tag me in the PR (I'll be on PTO next week, trying to keep up with emails but probably to avoid real work).

**Comment by Mardak** [comment] 2017-07-26 17:56
depends on what's needed for shield beta 56

**Comment by Mardak** [comment] 2017-07-26 18:10
Initial verbal example was en-US and de

**Comment by mariappopova** [comment] 2017-07-27 19:13
We will include Tier 1 (US, Canada, Germany) and Tier 2 (UK, Russia, Poland, France) locales in  56.

**Comment by Mardak** [comment] 2017-07-27 19:58
Currently those pontoon statuses:
en-US: source strings
en-CA: doesn't exist but just uses en-US
de: 100%
en-GB: 91%
ru: 91%, remaining strings have suggestions
pl: 100%
fr: 100%
https://pontoon.mozilla.org/projects/activity-stream-new-tab/

**Comment by flodolo** [comment] 2017-07-27 20:00
This is completely new to me: why are we not including other languages if they're completely localized? 

That wasn't called out when we exposed the project for localization, and for what it's worth I strongly disagree with this approach.

**Comment by flodolo** [comment] 2017-07-27 20:04
> EDIT: is this only for this specific Shield Experiment or it's going to happen for the feature itself?

Never mind, received an explanation via IRC. The list above only applies to the Shield Study for 56.

**Comment by Mardak** [comment] 2017-07-31 20:32
Sounds like zh-CN is being added for China (not sure about zh-TW). But in either case, these two locales are already 100% translated. And of the previously listed desired locales (en-US, de, ru, pl, fr, en-GB), they're all 100% translated except the migration strings for en-GB, which will fall back to en-US.

Default top sites approval are being tracked https://bugzilla.mozilla.org/show_bug.cgi?id=1385317
The various countries seem like they're mostly okay except unknown about China and Canada.

I believe the large icons for those top sites are being worked on by design.

Some related issues:
#3003 for using de for various de-* locales
#2944 for getting icons for those default sites

Marking this closed for now

**Closed by Mardak** 2017-07-31 20:32 UTC
Labels: Blocked, Fx56, P1

**Comment by Mardak** [comment] 2017-08-02 06:39
United States / en-US
![us](https://user-images.githubusercontent.com/438537/28860665-5b7b7546-7712-11e7-963d-b3bce6e66df5.png)
​
Canada / en-US
![canada](https://user-images.githubusercontent.com/438537/28860675-60a70c38-7712-11e7-938b-1afa82ff2954.png)

Germany / de
![germany](https://user-images.githubusercontent.com/438537/28860682-6743601e-7712-11e7-8d05-2e6dc1ef0de0.png)

France / fr
![france](https://user-images.githubusercontent.com/438537/28860685-6c57fa42-7712-11e7-9c2c-133acc5e9a0a.png)

Russia / ru
![russia](https://user-images.githubusercontent.com/438537/28860691-70a5b652-7712-11e7-9b96-1cbd47da91e6.png)

Poland / pl
![poland](https://user-images.githubusercontent.com/438537/28860697-74aeb0aa-7712-11e7-8648-3a563db8463a.png)

United Kingdom / en-GB
![uk](https://user-images.githubusercontent.com/438537/28860701-79006f54-7712-11e7-82de-85f93693db78.png)

Global - Taiwan / zh-TW
![taiwan](https://user-images.githubusercontent.com/438537/28860709-7ea44728-7712-11e7-9719-6b402c5392b8.png)
