### ISSUE TITLE
Broken New Tab and Blank Highlights on Activity Stream

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#1172] opened 2016-08-25 18:16 UTC
I started seeing the "Hang tight!" loading message and my New Tab has not been able to recover. Have attempted browser restart, system restart, disable/enable Activity Stream, disable/enable Test Pilot and still see the message. 

New Tab: https://cl.ly/1n2n1Y322B2h
Activity Stream: https://cl.ly/3b0h2K1z2D2H
Browser Console: https://cl.ly/0x3n3r0S0c1u

**Comment by pdehaan** [comment] 2016-08-25 20:10
Possible dupe of https://github.com/mozilla/activity-stream/issues/1139
Which means we should probably mark this/that as **CRITICAL** since more people than I are affected. I think I solved it by my Firefox crashing and re-running `npm run once` and creating a new profile.

**Comment by aaronrbenson** [comment] 2016-08-25 20:13
Is there anything besides grabbing my Browser Console output that would be helpful?

**Comment by aaronrbenson** [comment] 2016-08-25 22:29
And lo, it seems to have fixed itself ... *somehow*!

**Comment by aaronrbenson** [comment] 2016-08-26 15:52
Broken again. Same behavior as before. 😕

**Comment by edmoz** [comment] 2016-08-26 16:17
I get this when dev channel auto updates when it checks in the background, restarting often fixes this... But a bug we need to fix for sure.

**Comment by edmoz** [comment] 2016-08-29 18:04
this is a dupe of https://github.com/mozilla/activity-stream/issues/1139

**Closed by edmoz** 2016-08-29 18:04 UTC
Labels: Critical, P1
