### ISSUE TITLE
Load latency not being computed for every new tab

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1709] opened 2016-11-02 17:41 UTC
Using Activity Stream 1.1.5 from master @ commit: f6ecc5e1b9683806f6b5a48ffc7828ee383e3fc8

If I add a console.log after this line: 

https://github.com/mozilla/activity-stream/blob/master/addon/TabTracker.js#L299

console.log('\n\n\nLatency:', this._tabData.load_latency, '\n\n\n');

In previous versions of activity stream, this would cause the load latency for every new tab to be logged to the console, which indicates to me that we are capturing the load latency of the start of every new tab, which is how I believe our load latency monitoring is intended to work.

However, it no longer behaves this way on master.  Instead, if I have zero activity stream tabs open, and I open a new one, I will see a load latency as expected.  Then if I leave that tab open and open a second one, I do not see a load latency.  Opening any number of additional new tabs will never compute a load latency.  However, if I close all activity stream tabs and open a new one, I will see a load latency as expected.  

I think something about our shared state refactors is affecting the computation of load latency for each new tab.

**Comment by ncloudioj** [comment] 2016-11-08 20:57
I've tested this on both f6ecc5e and `master`, so the `latency` got logged in the console for every new tab(followed the steps described above). Haven't seen any significant drop of the total # of session pings in the Redshift either.

@jaredkerim can you still reproduce this on your machine?

**Comment by ncloudioj** [comment] 2016-11-15 17:48
Close this issue as we couldn't reproduce it any more.

**Closed by ncloudioj** 2016-11-15 17:48 UTC
Labels: P1
