### ISSUE TITLE
Highlights are misaligned on Timeline page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#1572] opened 2016-10-17 20:06 UTC
![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/19453510/662d88ac-946a-11e6-988e-4024012e95db.png)

![activity_stream_and_downloads_and____activity-stream___mozilla_and_amazon_com__dean_winchester_-_the_cw_s_supernatural_-_advanced_graphics_life_size_cardboard_standup](https://cloud.githubusercontent.com/assets/557895/19453483/4a3c039e-946a-11e6-8db0-260239256bbc.png)

---

Found in:
![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/19453492/52b95634-946a-11e6-8aeb-31bca23dba9c.png)

**Comment by Mardak** [comment] 2016-10-17 20:10
Duplicate of #1496.

**Closed by Mardak** 2016-10-17 20:10 UTC
