### ISSUE TITLE
Test pilot addon gives error in latest nightly

### ISSUE THREAD

**Issue by wlach** [mozilla/activity-stream#3055] opened 2017-08-01 15:35 UTC
With my Aug 1st nightly, I'm seeing this when I open a new tab with the test pilot addon:

![image](https://user-images.githubusercontent.com/20569/28833479-7325bffe-76ad-11e7-83e5-b1aa0aa3d254.png)

(was seeing the same July 31st)

It looks like the test pilot version of activity stream is being retired? Do we need to do something to explicitly disable it / mark it as incompatible?

**Comment by Mardak** [comment] 2017-08-01 15:56
If you're on linux, this is dupe of #2966. See https://bugzilla.mozilla.org/show_bug.cgi?id=1384240

**Comment by Mardak** [comment] 2017-08-01 15:57
In particular, test pilot add-on is being retired, but should still work. The sandboxing feature just added is not quite working correctly on linux.

**Closed by Mardak** 2017-08-01 15:56 UTC

**Comment by wlach** [comment] 2017-08-01 16:39
Yup! Looks like a dupe.
