### ISSUE TITLE
Navigating to about:newtab with back button breaks the new tab's search box

### ISSUE THREAD

**Issue by cpeterso** [mozilla/activity-stream#2042] opened 2017-01-18 22:34 UTC
STR:
1. Open a new tab with Activity Stream enabled.
2. In the new tab's search box, enter a search phrase and press the ENTER key.
3. Watch Firefox open a search results page.
4. Click the Firefox back button to return to the new tab page.
5. Enter a different search phase in the new tab's search box and press the ENTER key.

RESULT:
Nothing happens. The new tab's search box does not show the search provider list and pressing the ENTER key does not initiate a new search.

**Comment by Softvision-VladBacia** [comment] 2017-01-19 10:05
Hi Chris. This issue seems to be related with #836. 

We verified this issue, mentioned by you, on Windows 8.1 x64, Mac OS X 10.12, Ubuntu 14.04 with latest Nightly (Build ID: 20170118030214) and latest Firefox release v50.1.0 using AS 1.3.0-dev-1484785252 and couldn't reproduce the issue with the search not been initiated. The issue with search suggestions drop-down is reproducible, as mentioned in #836.

1. On what OS did you encounter this problem and what version of AS did you use?
2. AS was installed from Test Pilot? or from latest dev?
3. Ar there any custom changes to the Firefox profile?

**Comment by cpeterso** [comment] 2017-01-19 20:24
I am running Activity Stream version 1.2.0 in Firefox 50 release and Nightly 53 on Windows 10. I can reproduce in a clean Firefox profile.

**Comment by sarracini** [comment] 2017-04-13 19:37
Closing this since we won't be able to use the back button with about:newtab shortly

**Closed by sarracini** 2017-04-13 19:37 UTC
Labels: Bug, MVP, P1
