### ISSUE TITLE
Consider removing the option to "Prevent this page from creating additional dialogs"

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#1098] opened 2016-08-16 20:54 UTC
Issue 1
The checkbox to "Prevent this page from creating additional dialogs" should probably not exist on Activity Stream since the confirm dialog is the only way to actually delete items from history. If you check that option, you are subsequently no longer able to delete items ... until ...

Issue 2
... a page refresh occurs and it seems the flag for preventing the page from creating dialogs is reset. Which means the checkbox has one job to do and it doesn't do it that well.

Follow along here: https://cl.ly/1y2x453d0N0D

**Comment by pdehaan** [comment] 2016-08-16 21:03
Interesting, we did have https://github.com/mozilla/activity-stream/issues/413 which outlined replacing the whimsically horrible UX of the `alert()` with a custom dialog, but for some reason that was closed.

**Comment by SoftVision-PaulOiegas** [comment] 2016-08-19 11:28
Maybe a dupe of #832 ?

**Comment by jaredkerim** [comment] 2016-08-22 17:33
Closing as a duplicate.

**Closed by jaredkerim** 2016-08-22 17:33 UTC
