### ISSUE TITLE
Collapse redirected top sites and combine their frecency

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#1388] opened 2016-09-23 00:08 UTC
Split from #1311. moz_placeshistory has referrer information that could be used.

**Comment by Mardak** [comment] 2016-09-29 20:47
The top frecent sites query already includes `hidden = 0` which should prevent a page that is only redirected to from showing up.

**Comment by jaredkerim** [comment] 2017-01-23 19:14
This is blocked on being able to confidently reproduce it.

**Comment by sarracini** [comment] 2017-01-27 15:17
Closing this since we can't reproduce this, and we will re-open if we find an issue with redirects

**Closed by sarracini** 2017-01-27 15:17 UTC
Labels: Blocked, P1
