### ISSUE TITLE
Remove Bookmarks queries

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1505] opened 2016-10-11 15:12 UTC
We will no longer need to query bookmarks PlacesDB, so let's remove it from PlacesProvider, as we all as the asyncCache stuff in ActivityStreams.js

[edit @k88hudson to split up tickets]

**Comment by k88hudson** [comment] 2016-10-11 17:11
This is actually a dupe of https://github.com/mozilla/activity-stream/issues/1501

**Closed by k88hudson** 2016-10-11 17:11 UTC
