### ISSUE TITLE
In some tabs loading message repeats forever

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#1759] opened 2016-11-09 17:09 UTC
I've seen this on two machines now.  Interestingly, it happens on a single tab, while opening a new tab correctly renders highlights etc, even as the repeating one goes on forever.  This particular version is 1.1.7-dev-1478631126.

Video: https://api.monosnap.com/rpc/file/download?id=4uAptxdPsiV8vbiejNrEaazxJoLwKj

I don't know what the steps-to-reproduce are.  That said, if this is common, it might want to block shield.

Only obviously related message in the browser console is a "tab updated" from bootstrap.js on every refresh.

**Comment by jaredkerim** [comment] 2016-11-14 19:16
Closing as a duplicate of #1778

**Closed by jaredkerim** 2016-11-14 19:16 UTC
