### ISSUE TITLE
Top sites query is missing bookmark data (Bug 1279928) 

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#847] opened 2016-06-13 15:53 UTC
It looks like we are not joining the query for Top sites (i.e. `getTopFrecentSites` in `PlacesProvider.js`) on the bookmarks table, so we don't get information about whether a top site is bookmarked or not. We should add this.

_Edited by @k88hudson for clarity_
_-----------_

After refreshing the New Tab page, "Bookmark" option is available for a previously bookmarked item from "Top Sites"

via https://bugzilla.mozilla.org/show_bug.cgi?id=1279928

<hr>

[Affected versions]:
- Firefox 45 and up
- Activity Stream 1.1.0-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on (v1.1.0-dev) was previously installed on a clean profile.
- Have enough history so that the "Top Sites" area is populated with visited websites.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Click on "+" to open a new tab.
3. Hover on one of items from Top Sites, and then click on the "..." button.
4. Choose the "Bookmark" option, and refresh the page.
5. Click the "..." button, from the previously bookmarked item.

[Expected result]:
- The "Remove Bookmark" option is available for the bookmarked item.

[Actual result]:
- After the refresh is made, "Bookmark" option is displayed instead of "Remove Bookmark" in the context menu. 

[Notes]:
- The issue can be observed [here](https://bug1279928.bmoattachments.org/attachment.cgi?id=8762556).

**Comment by SoftVision-CiprianMuresan** [comment] 2016-10-20 14:08
The issue is still reproducible on the latest version (1.1.5).  Attaching a [screen recording](https://goo.gl/UEWMIO).

**Comment by sarracini** [comment] 2017-01-17 22:21
Closing this since it does now

**Closed by sarracini** 2017-01-17 22:21 UTC
Labels: Bugzilla, Good first bug, P2

**Comment by Softvision-VladBacia** [comment] 2017-01-18 15:03
This issue is no longer reproducible in Activity Stream Dev 1.3.0-dev-1484695187.
