### ISSUE TITLE
[Enhancement] Consider showing more recent Highlights instead of "blocked" Bookmarks

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3757] opened 2017-10-24 13:58 UTC
https://bugzilla.mozilla.org/show_bug.cgi?id=1411260

[Affected versions]:
- Firefox 58.0a1 Build ID 20171022220103
- Firefox 57.0b10

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Chrome profile with enough History to populate Top Sites and at least 9 bookmarks.

[Steps to reproduce]:
1. Start the browser with a new profile.
2. Import History from Chrome.
3. Visit many different pages over the course of two days.
4. Observe the Highlights section.
 
[Expected results]:
- More recent pages should be displayed.

[Actual results]:
- The pages that were bookmarked are "blocked" in the section.

[Notes]:
- This behavior is also reproducible if you sync with an account that has history. Or it can appear naturally after you make multiple bookmarks at the same time.
- The bookmarked pages from Highlights are changed after about 3 days. We should consider showing more recent content if the user chooses to bookmark many pages at once.

**Comment by Mardak** [comment] 2017-10-24 18:25
What do you mean by "blocked"? The bookmarks are occupying the space so you end up with 9 bookmarks and no history?

**Comment by SoftVision-CiprianMuresan** [comment] 2017-10-25 08:47
They're not blocked in a literal sense and yes, you make 9 bookmarks and then regardless of how many pages you visit, the bookmarks will be displayed in Highlights until they are no longer recent enough to be shown. But this means you have the same 9 bookmarks for a few days in a row (unless you bookmark more pages, then the new bookmarks take the place of the older less recent ones).

What I'm trying to say here is that we should consider showing more recent content in the highlights section if a bookmark is in the same place for too long.

**Comment by aaronrbenson** [comment] 2017-10-25 20:36
This behavior is currently by design but we have plans to implement a better weighted Highlights system ASAP and is being tracked in our Trello board, here: https://trello.com/c/0Hz8vHe2/163-i-want-to-have-weighted-highlights

**Comment by tspurway** [comment] 2017-10-30 18:24
closing - intended

**Closed by tspurway** 2017-10-30 18:24 UTC
Labels: Bugzilla
