### ISSUE TITLE
Unhandled rejection in SearchProvider.js

### ISSUE THREAD

**Issue by ckarlof** [mozilla/activity-stream#735] opened 2016-05-23 20:43 UTC
```
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Mon May 23 2016 13:37:03 GMT-0700 (PDT)
Full Message: TypeError: ContentSearch._currentStateObj is not a function
Full Stack: get state/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/SearchProvider.js:55:25
TaskImpl_run@resource://gre/modules/Task.jsm:319:40
TaskImpl@resource://gre/modules/Task.jsm:280:3
createAsyncFunction/asyncFunction@resource://gre/modules/Task.jsm:254:14
Task_spawn@resource://gre/modules/Task.jsm:168:12
get state@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/SearchProvider.js:54:12
_respondToSearchRequests@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/ActivityStreams.js:161:9
EventEmitter_emit@resource://devtools/shared/event-emitter.js:163:13
_setupPageMod/this._pagemod<.onAttach/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/ActivityStreams.js:400:11
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
receive@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/content/worker.js:74:26
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:123:45
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
messageReceived@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/remote/parent.js:96:37
```

[/lib/SearchProvider.js:55](https://github.com/mozilla/activity-stream/blob/3523ca26dbb4fc29156d696af9d47ae6e7651234/lib/SearchProvider.js#L55)

**Comment by sarracini** [comment] 2016-05-24 14:09
this is a dupe of #706

**Closed by sarracini** 2016-05-24 14:09 UTC
