### ISSUE TITLE
Bug 1267556 - Highlights tiles are not populated since default websites were added in New Tab and Timeline pages

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#612] opened 2016-05-02 17:17 UTC
via https://bugzilla.mozilla.org/show_bug.cgi?id=1267556
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.12

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.12) was previously installed on a clean profile.  

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Visit some pages that would appear in Highlights section. (eg. YouTube videos)
3. Click the Activity Stream button from the browser toolbar.
4. Observe the Highlights tiles from the Timeline page.

[Expected result]:
The Highlights tiles are populated with content from the visited webpages.

[Actual result]:
The default Mozilla pages are stuck in Highlights section and can not be replaced.

[Notes]:
- The issue is reproducible on the New Tab page as well.
- Attached a screen recording of the issue.

**Comment by pdehaan** [comment] 2016-05-02 17:22
May be a dupe of #570

**Comment by pdehaan** [comment] 2016-05-04 20:53
@nchapman were you triage/verifying this, or should we bump to post v1?

**Comment by nchapman** [comment] 2016-05-09 16:14
This is due to the fact that we don't start showing history items in highlights for 30 minutes. It's hardly ideal, but we decided this is the best behavior for most of our early users. Bumping this to post v1 as we need to revisit this.

**Closed** 2016-05-16 18:00 UTC
Labels: Bugzilla, Design feedback needed
