### ISSUE TITLE
Bug 1279920 - The Search Suggestion dropdown flashes when the New Tab page is refocused

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#845] opened 2016-06-13 15:46 UTC
via https://bugzilla.mozilla.org/show_bug.cgi?id=1279920

<hr>

[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.1.0-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.1.0-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Open a New Tab and write a keyword in the Search bar.
3. Click the Windows Task bar.
4. Click back on the New Tab page and observe the Search bar.

[Expected result]:
- The Search bar is no longer focused.

[Actual result]:
- After the New Tab page receives focus, the Search Suggestion dropdown is displayed for a second and then it disappears.

[Notes]:
- [Here](https://bugzilla.mozilla.org/attachment.cgi?id=8762544), is a screen recording of the issue.

**Comment by sarracini** [comment] 2017-01-13 21:25
I can no longer reproduce this, @Softvision-VladBacia can you?

**Comment by sarracini** [comment] 2017-01-17 22:22
Closing this as I can no longer reproduce this

**Comment by Softvision-VladBacia** [comment] 2017-01-18 15:00
This issue has been verified on Activity Stream Dev 1.3.0-dev-1484695187. 

- On Mac OS X when the browser window is unfocused the search suggestion drop-down list is closed and when is focused again the drop-down list is displayed. 
- On Windows and Ubunt, when the window is refocused the search suggestion drop-down list is displayed for ~1s and then it is closed.

The behavior should be consistent on all OSs.  On Windows and Ubunt when the browser is refocused the search suggestion drop-down list should be displayed.

**Comment by k88hudson** [comment] 2017-06-27 23:54
Is this still a problem on the system add-on?

**Comment by SoftVision-CiprianMuresan** [comment] 2017-06-28 12:43
No, the issue is not reproducible on the system add-on version. Tested on Windows, Mac and Ubuntu. I think we can close this.

**Closed** 2017-06-28 16:26 UTC
Labels: Bug, Bugzilla, P3, Polish, Search
