### ISSUE TITLE
Top site missing #1 facebook page

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#1876] opened 2016-12-19 18:39 UTC
@emtwo's `about:newtab` shows Facebook but it's nowhere to be seen in Activity Stream top sites.

@emtwo, can you confirm the url being shown on your `about:newtab` page? Also, if you dismiss enough, do you eventually see a facebook link?

**Comment by Mardak** [comment] 2016-12-19 18:59
You can try debugging with this query from the console in `about:newtab`:

```js
Cu.import("resource://gre/modules/PlacesUtils.jsm"); PlacesUtils.promiseDBConnection().then(db => db.execute(`SELECT url, title, frecency, guid, bookmarkGuid,
                          last_visit_date / 1000 as lastVisitDate, favicon, mimeType,
                          "history" as type
                    FROM
                    (
                      SELECT
                        CASE SUBSTR(rev_host, -5)
                          WHEN ".www." THEN SUBSTR(rev_host, -4, -999)                  
                          ELSE rev_host
                        END AS rev_nowww,                                               
                        moz_places.url,
                        moz_favicons.data AS favicon,                                   
                        mime_type AS mimeType,                                          
                        moz_places.title,                                               
                        frecency,
                        last_visit_date,
                        moz_places.guid AS guid,
                        moz_bookmarks.guid AS bookmarkGuid                              
                      FROM moz_places
                      LEFT JOIN moz_favicons
                      ON favicon_id = moz_favicons.id                                   
                      LEFT JOIN moz_bookmarks
                      on moz_places.id = moz_bookmarks.fk
                      WHERE hidden = 0 AND last_visit_date NOTNULL                      
                      ORDER BY rev_host, frecency, last_visit_date, moz_places.url DESC 
                    )
                    GROUP BY rev_nowww
                    ORDER BY frecency DESC, lastVisitDate DESC, url                     
                    LIMIT 100`).then(v => console.log(v.map(r => [r.getString(0), r.getInt32(2)]).join("\n"))))
```

**Comment by jaredkerim** [comment] 2016-12-19 19:03
Closing as a duplicate of #1874

**Closed by jaredkerim** 2016-12-19 19:03 UTC
