### ISSUE TITLE
Bug 1279487 - Search suggestions are no longer displayed after performing a search and returning to New Tab page

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#836] opened 2016-06-10 12:25 UTC
via https://bugzilla.mozilla.org/show_bug.cgi?id=1279487

<hr>

[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.19-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.19-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Open a New Tab and write something in the "Search" bar.
3. Press the "Enter" key.
4. Click on "Back" button to return to New Tab page.
5. Write a keyword in the search textbox and observe the behavior.

[Expected result]:
The search suggestion dropdown is updated with the new string.

[Actual result]:
The search suggestion dropdown is not displayed and will not be displayed when adding keywords.

[Notes]:
- If you click outside the search bar and then back to it, the search suggestion dropdown appears.
- Attached a screen recording of the issue https://goo.gl/bGiVBK.

**Comment by sarracini** [comment] 2016-06-10 13:47
Closing this as a dupe of #812

**Comment by SoftVision-VladBacia** [comment] 2016-06-10 14:43
This issue is slightly different from #812 . Through this scenario we described the wrong behavior of the Search suggestion dropdown menu. 

The Search suggestion dropdown menu is no longer displayed for any keyword that will be written if a search was performed using the "Enter" button.

**Comment by sarracini** [comment] 2017-01-13 21:23
I can no longer reproduce this @Softvision-VladBacia , can you?

**Comment by sarracini** [comment] 2017-01-17 22:22
Closing this since I can no longer reproduce it

**Comment by Softvision-VladBacia** [comment] 2017-01-18 13:50
This issue is reproducible in Activity Stream Dev 1.3.0-dev-1484695187. After returning to AS New Tab page, I've selected the whole word written in the Search bar and replaced with another one. At this point, the search suggestion drop-down list is not displayed. [Here](https://drive.google.com/open?id=0B6QogV2AJFKiQXB2NFpmYnF0Umc) is a video of the issue.

**Comment by k88hudson** [comment] 2017-04-07 15:08
Closing as wont fix since the back button is no longer available in the system-addon version of Activity Stream.

**Closed by k88hudson** 2017-04-07 15:08 UTC
Labels: Bug, Bugzilla, P3, Polish, Search
