### ISSUE TITLE
Section placeholders are no longer displayed if Search, Top Sites or Highlights are disabled

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3737] opened 2017-10-19 11:23 UTC
https://bugzilla.mozilla.org/show_bug.cgi?id=1410031

[Notes]:
- If you have Top Sites on two rows the placeholders force the sections to jump around because it only shows a single row of Top Sites. There should be two rows of placeholders if the user has Top Sites on two rows.

[Affected versions]:
- Firefox 58.0a1 Build ID 20171018220049

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the browser and open a new window.
2. Disable the Search bar from the customization panel.
3. Open a new window and observe the behavior.
4. Open a new tab and observe the behavior.

[Expected results]:
- Step 3 & 4: The placeholders are displayed before the content is loaded.

[Actual results]:
- Step 3 & 4: The page is empty and then content appears.

[Additional notes]:
- The issue became more apparent after bug 1383593 was fixed.
- The issue is also reproducible if the Top Sites or Highlights sections are disabled, or if any combination of two sections (eg. Search + Highlights) are disabled.
- Attached a screen recording of the issue:
![placeholders no longer displayed if search top sites or highlights are disabled](https://user-images.githubusercontent.com/18304511/31768670-09f2078a-b4d9-11e7-8101-dc1ea00ede9e.gif)

**Comment by Mardak** [comment] 2017-10-23 18:38
This should be fixed by / dupe of #3367. The core issue is that we show a non-prerendered page when certain preferences are changed.

**Closed by Mardak** 2017-10-23 18:38 UTC
Labels: Bugzilla, fx59, P3
