### ISSUE TITLE
Optimize (and resize) images in lib/ShareManifests.js?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#1097] opened 2016-08-16 20:13 UTC
Ref: https://github.com/mozilla/activity-stream/pull/1070#issuecomment-240218126,

Currently a few of the images seem unoptimized and sizing is off.

You can find my horrific code snippets in https://github.com/mozilla/activity-stream/pull/1070#issuecomment-240186237 and https://github.com/mozilla/activity-stream/pull/1070#issuecomment-240198125 for extracting the embedded data:uris into external files, and running them through imagemin+zopfli (and then injecting the optimized assets back into ShareManifests.js).

---

Similarly, a few of the images are unexpected sizes:

``` js
const fs = require('fs');

const Datauri = require('datauri').sync;
const sizeOf = require('image-size');

const ShareManifests = require('./ShareManifests');

for (let manifest in ShareManifests) {
  ['iconURL', 'icon32URL', 'icon64URL'].forEach((icon) => {
    const imagePath = `optimized/${manifest}-${icon}.png`;
    const {height, width} = sizeOf(imagePath);
    ShareManifests[manifest][icon] = Datauri(imagePath);
    console.log(`${imagePath} - w:${width}, h:${height}`);
  });
}

fs.writeFileSync('ShareManifests.js', JSON.stringify(ShareManifests, null, 2));
```

| IMAGE | W | H | NOTES |
| --- | :-: | :-: | --- |
| optimized/social.manifest.twitter-com-iconURL.png | 16 | 16 |  |
| optimized/social.manifest.twitter-com-icon32URL.png | 32 | 32 |  |
| optimized/social.manifest.twitter-com-icon64URL.png | 64 | 64 |  |
| optimized/social.manifest.www-facebook.com-iconURL.png | 16 | 16 |  |
| optimized/social.manifest.www-facebook.com-icon32URL.png | 32 | 32 |  |
| optimized/social.manifest.www-facebook.com-icon64URL.png | 58 | 58 | This isn't 64x64 |
| optimized/social.manifest.mg-mail.yahoo.com-iconURL.png | 16 | 16 |  |
| optimized/social.manifest.mg-mail.yahoo.com-icon32URL.png | 32 | 32 |  |
| optimized/social.manifest.mg-mail.yahoo.com-icon64URL.png | 64 | 64 |  |
| optimized/social.manifest.mail-google.com-iconURL.png | 16 | 16 |  |
| optimized/social.manifest.mail-google.com-icon32URL.png | 32 | 32 |  |
| optimized/social.manifest.mail-google.com-icon64URL.png | 64 | 64 |  |
| optimized/social.manifest.www-linkedin.com-iconURL.png | 16 | 16 |  |
| optimized/social.manifest.www-linkedin.com-icon32URL.png | 30 | 25 | This isn't 32x32 |
| optimized/social.manifest.www-linkedin.com-icon64URL.png | 60 | 50 | This isn't 64x64 |
| optimized/social.manifest.www-tumblr.com-iconURL.png | 16 | 16 |  |
| optimized/social.manifest.www-tumblr.com-icon32URL.png | 32 | 32 |  |
| optimized/social.manifest.www-tumblr.com-icon64URL.png | 64 | 64 |  |

**Comment by rlr** [comment] 2016-08-16 20:21
We should also look into including the actual image files in the xpi and point to them or load them via CSS. (as suggested by @mixedpuppy)

This would make the manifest prefs much smaller and take care of these warnings that currently show up:

```
Warning: attempting to write 8984 bytes to preference social.manifest.twitter-com. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
Warning: attempting to write 8755 bytes to preference social.manifest.www-facebook.com. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
Warning: attempting to write 12990 bytes to preference social.manifest.mg-mail.yahoo.com. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
Warning: attempting to write 5306 bytes to preference social.manifest.mail-google.com. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
Warning: attempting to write 6544 bytes to preference social.manifest.www-linkedin.com. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
```

**Comment by pdehaan** [comment] 2016-08-16 21:11
Not sure if it's just me, but the inlined PNG icons look kind of blurry on my retina Macbook Pro.

<img width="244" alt="latest_activity_stream_experiment_addon" src="https://cloud.githubusercontent.com/assets/557895/17715878/112dc00e-63bb-11e6-80d9-993815779391.png">

**Comment by mixedpuppy** [comment] 2016-08-16 21:16
I've a suspicion that new icon sizes are 18x18, whereas the icons from socialapi are 16x16.  I haven't confirmed it, but those are indeed blurry.  I know toolbar icons changed to 18x18 except for addons I think, where they are 16x16.

**Comment by pdehaan** [comment] 2016-08-16 21:16
@mixedpuppy @rlr Is there a spec somewhere I can read that discusses the options for the lib/ShareManifest.js stuff?

Looking at the screenshot above, it looks like the LinkedIn icon is square and nice, but looking at the `icon64URL` data:uri in a browser, it has a little (r) trademark symbol on it, which makes me wonder if our share doorhanger is using the 16x16, 32x32, or 64x64 image.

If it's somehow using the 16x16, that may explain why they don't look retina capable for me locally.

**Comment by pdehaan** [comment] 2016-08-16 21:19
... apart from me just reverting to big red squares for 16x16, green for 32x32, and blue for 64x64 and trying to prove to myself that it's in fact choosing the highest quality icon. But having the docs/schema for what the values are would definitely help.

I found https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#iconURL but that looks like its just for the install manifest and not this stuff specifically.

**Comment by mixedpuppy** [comment] 2016-08-16 21:20
The socialapi icons are indeed 16x16 (in the panel).

**Comment by sarracini** [comment] 2017-04-17 18:40
Closing this since share is gone

**Closed by sarracini** 2017-04-17 18:40 UTC
Labels: P3
