### ISSUE TITLE
Collect metrics around URL caching/embedly calls

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#680] opened 2016-05-11 20:48 UTC
I would like to collect metrics from the addon that are reported to onyx surrounding URLs that come from places db, are looked up in the simplestorage cache, and are eventually requested from the embedly proxy.  We must not send actual URLs in any metrics pings as that will violate user privacy.  An example of the metrics I would like to collect are:

In this code segment: https://github.com/mozilla/activity-stream/blob/master/lib/ActivityStreams.js#L150-L155

    {
        source: "TOP_FRECENT_SITES_RESPONSE",  // which SQL query produced this list of URLs
        count: 17, // the total number of URLs returned by the SQL query
        cacheHit: 13, // the number found in our local simple storage cache
        cacheMiss: 4, // the number we failed to find and will request from embedly-proxy
    }

In this code segment: https://github.com/mozilla/activity-stream/blob/master/lib/PreviewProvider.js#L279-L308

    {
        success: true, // was the call to embedly-proxy successful
        urlsRequested: 4, // how many URLs did we send to the proxy
        urlsReceived: 2, // how many URLs did we get back
        requestLatency: 13.4, // how long did it take for the call to complete
    }

The embedly proxy collects logs and metrics around calls it receives, whether they were successful, and calls out to embedly, however I would also like to collect similar metrics on the client side to get a clearer understanding of whether the client is behaving correctly and receiving the data it receives or whether it is failing to find the data it wants correctly.

@oyiptong @k88hudson thoughts?

**Comment by sarracini** [comment] 2016-05-16 14:58
Closing this since it's a dupe of #705

**Closed by sarracini** 2016-05-16 14:58 UTC
