### ISSUE TITLE
Activity Stream performance issues 

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/activity-stream#1420] opened 2016-09-30 00:41 UTC
The most recent build of Activity Stream has been sucking my memory and CPU dry, bringing Firefox over 8 GB RAM.
- about:performance had it using 48% of my CPU, with a 10/10 impact on framerate
- about:memory had some Activity Stream processes using "unreasonably high" amounts of RAM. I tried to capture a memory report, but it completely locked the browser up.
- After the lockup I disabled Activity Stream, restarted Firefox, and it's back to normal.

_(NB: I maintain a very light browser footprint; half a dozen add-ons, infrequently any more than a dozen tabs.)_

**Comment by Softvision-VladBacia** [comment] 2016-09-30 14:32
@chuckharmston , I can confirm this issue. 
- I've tested with latest Firefox release 49.0.1 and latest Nightly 52.0a1 and when Activity Stream is enabled the overall performance of the browser is affected. When opening a new tab, the tab animation is choppy compared to the same action where Activity Stream is not installed. Also the RAM usage in my case was about 3GB. 

- Another thing that I've noticed is that when I've accessed different websites, they were loading slower compared to a browser instance that doesn't have Activity Stream.

**Comment by ncloudioj** [comment] 2016-09-30 20:25
Could you give us more info about the context please? like the OS, add-on version (dev/release) etc. It'll be super helpful for us to reproduce the issue.

Thank you in advance!

**Comment by chuckharmston** [comment] 2016-09-30 20:28
OS X, updated Dev Edition, latest Activity Stream from production.

**Comment by k88hudson** [comment] 2016-09-30 20:35
Hmm, sounds like it could be a memory leak

**Comment by Softvision-VladBacia** [comment] 2016-10-03 09:20
I have tested the issue on Windows 8.1 with Activity Stream-dev build.

**Comment by xenithorb** [comment] 2016-10-04 11:30
I tried to provide feedback but all I got was a survey (that I filled out) and no way to explain the real problem I am having. 

The addon is great, I love it, and it gives me an easy picture to get back to things I previously was looking at - the problem is that my workflow is to quickly make a new tab and search in the address bar - *which has been hindered by this addon due to the fact that it causes the browser to lag and prevents me from quickly typing in a search while the activity stream is being rendered.*

**Comment by ncloudioj** [comment] 2016-10-04 15:00
@xenithorb Thank you for your feedback.

Sorry to hear that this addon has given your difficulty on browsing. Unfortunately, the addon has been experiencing some performance issues lately. We're currently working on fixing them, and stabilizing the performance. A couple of patches have already landed in the dev build, you can try it out at [here](https://moz-activity-streams-dev.s3.amazonaws.com/dist/latest.html). We'd appreciate any further feedback from you.

**Comment by xenithorb** [comment] 2016-10-04 16:10
Right on, I was just looking for a way to inform the project of why I had to disable it temporarily. I'll be waiting for a new stable version

**Comment by SoftVision-PaulOiegas** [comment] 2016-10-07 14:04
A Bugzilla issue was also logged by Markus Stange for performance issues that involves also Activity Stream.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1308326 .

**Comment by ehsan** [comment] 2016-10-07 15:25
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1308332 which has a lot more technical details.

**Comment by k88hudson** [comment] 2016-11-07 20:02
I'm closing this, we will filing new performance tickets with specific updates.

**Closed** 2016-11-07 20:01 UTC
Labels: Critical, P1, Performance
