### ISSUE TITLE
Allow searching in the activity

### ISSUE THREAD

**Issue by marco-c** [mozilla/activity-stream#720] opened 2016-05-18 12:14 UTC
It's a good feature of the `Library` which is missing from Activity Stream

**Comment by softvision-VladBacia** [comment] 2016-05-18 12:37
Hi @marco-c , thank you for reporting this. In my opinion this issue is similar with #676 .

**Comment by sarracini** [comment] 2016-05-25 17:00
this is a dupe of #743

**Closed by sarracini** 2016-05-25 17:00 UTC
Labels: Design feedback needed
