### ISSUE TITLE
Allow blocking default top sites (Bug 1270411)

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#639] opened 2016-05-05 08:35 UTC
via https://bugzilla.mozilla.org/show_bug.cgi?id=1270411

<hr>

[Notes]:
- In my opinion, the fact that the user is unable to remove one of the default websites when it has the option is a bad UX. Since we don't want to have an empty placeholder, one good option, of course if possible, could be to never display a remove option for the 6 websites links even if they are visited. 
- Added a screen recording with the issue https://goo.gl/lbnIY2 .

[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.14-dev-1462316117

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.14-dev-1462316117) was previously installed on a clean profile.  

[Steps to reproduce]:
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Open a "New Tab" page and click on one of the top sites that are displayed by default.
3. Open another "New Tab" page and hover over the opened website from "Top Sites" area.
4. Click the "(x)" button from top right corner of the tile and chose to remove / never show it.
5. Refresh the "New Tab" page and observe the website behavior in "Top Sites" area.

[Expected results]:
Step 4 -The default websites should not gain remove option even if visited (history created). 

[Actual results]:
The removed default website reappears in "Top Sites" area.

**Comment by oyiptong** [comment] 2016-06-27 18:17
We will fix this bug because we want to follow the user's decision to block the site

**Comment by Standard8** [comment] 2016-07-28 11:11
I've just tried this on v1.1.1 of the add-on. It seems to be working fine here.

I click the "...", click the "X Dismiss" option, then I reload the page. The site is not in the top sites list.

@SoftVision-PaulOiegas can you try and see if my results are the same as yours now?

**Comment by sarracini** [comment] 2017-05-11 17:09
Closing this as a dupe of #2414

**Closed by sarracini** 2017-05-11 17:09 UTC
Labels: Bug, Bugzilla, Good first bug, MVP, P2
