### ISSUE TITLE
Make all sections collapsible

### ISSUE THREAD

**Issue by rlr** [mozilla/activity-stream#3261] opened 2017-08-28 17:41 UTC
We need to port over the `CollapsibleSection` component from test pilot addon. It probably needs some changes to handle the new custom sections.

**Comment by Mardak** [comment] 2017-08-28 18:10
P2 as there's an alternative to completely turn off sections.

**Comment by sarracini** [comment] 2017-08-28 19:00
This is actually a dupe of #3148

**Closed by sarracini** 2017-08-28 19:00 UTC
Labels: fx57, P2

**Comment by rlr** [comment] 2017-08-28 19:02
gah I searched for "collapsible" instead of "collapsed". github should have smarter search 😃
