### ISSUE TITLE
Enabling "Activity Stream" and "Universal Search" from the Test Pilot Page fails

### ISSUE THREAD

**Issue by Mikhej** [mozilla/activity-stream#754] opened 2016-05-27 02:55 UTC
Trying to enable "Activity Stream" from https://testpilot.firefox.com/experiments/activity-stream and "Universal Search" from https://testpilot.firefox.com/experiments/universal-search is sitting in indefinite loop. Both page display "Enabling" indefinitely.
From the three areas of Test Pilot only "Tab Center" works

**Comment by SoftVision-VladBacia** [comment] 2016-05-27 07:19
@Mikhej Thanks for reporting this. A couple other users have reported this as well and the issue is being investigated.

For more information, you can follow this **Test Pilot** issue: mozilla/testpilot#843

Closing in favor of upstream Test Pilot bug.

**Closed by SoftVision-VladBacia** 2016-05-27 07:19 UTC
