### ISSUE TITLE
Can't add articles to Pocket from Activity Stream after Firefox 57 update.

### ISSUE THREAD

**Issue by smartfonreddit** [mozilla/activity-stream#3107] opened 2017-08-07 20:50 UTC
The button to add articles to Pocket has stopped working from Activity Stream (the only option enabled in New Tab Preferences) around August 2nd. There was a similar problem few weeks ago but that was related to Pocket being broken completely without the ability to add articles from anywhere. This time the problem is only on Activity Stream.

Using latest Nightly on Windows 10.

**Comment by sarracini** [comment] 2017-08-08 15:38
@smartfonreddit did you remove the Pocket button from your toolbar by any chance?

**Comment by sarracini** [comment] 2017-08-08 15:44
It seems as though since the pocket icon isn't displayed in the toolbar anymore for newtab pages, this function just returns early: http://searchfox.org/mozilla-central/source/browser/extensions/pocket/content/Pocket.jsm#98 since ```placement``` is null 
as a result, the function ```savePage``` which we call into here: https://github.com/mozilla/activity-stream/blob/master/system-addon/lib/PlacesFeed.jsm#L225 does nothing

**Comment by sarracini** [comment] 2017-08-08 15:48
Newtab toolbar: 
![newtabtoolbar](https://user-images.githubusercontent.com/7219526/29081026-675ee272-7c2f-11e7-8fcc-dd8e10c7803f.png)

All other pages toolbar:
![notnewtabtoolbar](https://user-images.githubusercontent.com/7219526/29081036-7177ac4e-7c2f-11e7-8bb5-7096b4ed5e83.png)

The code looks for that icon and then opens up a drop down to let you save the article, without that icon, the function does nothing :(

**Comment by smartfonreddit** [comment] 2017-08-08 15:53
I did remove the {ocket icon from the toolbar, and there is no icon inside the address bar while in New Tab. Restoring Defaults from the customize mode doesn't bring back the Pocket icon. I was trying to place it on the toolbar again.

**Comment by sarracini** [comment] 2017-08-08 19:04
Actually, I believe this is a dupe of ticket #2626, as this is the same problem in both cases, so let's close this and just move the discussion into that ticket. Thanks @smartfonreddit!

**Closed by sarracini** 2017-08-08 19:04 UTC
Labels: Design feedback needed
