### ISSUE TITLE
Clicking the ActivityStream/Timeline icon in the menubar doesn't always show the ActivityStream

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#253] opened 2016-03-02 22:33 UTC
... at least in the focused window.

I was testing a recent PR and randomly trying to get some browsing data by clicking random links and think I found a weird case where if you click something like `<a href="http://www.google.com/policies/privacy/" target="_blank">Google Privacy Policy</a>` then it opens a new window (see `target=_blank`) but then if I click the ActivityStream/Timeline button, it seems to open the page in the calling window, not the current window.

### Steps to reproduce:
1. Go to https://payments.google.com/legaldocument?family=0.privacynotice
1. Click the ActivityStream/Timeline button in the menu bar.
2. Click the "Google Privacy Policy" link in the original tab.
3. In the new window, click the ActivityStream/Timeline button.

### Actual results:
The ActivityStream/Timeline page is opened in the ORIGINAL window, not the currently focused window where I clicked the icon. I clicked the icon thinking something broke and it was a noop, only to find I opened 5 tabs in my original Firefox window which was in the background.

### Expected results:
The Timeline page should always appear in the current window where you clicked the icon.
This all seems to be dependent on whether you clicked the ActivityStream button in the original window. Very weird.

---

![banners_and_alerts_and_privacy_policy_ _privacy___terms_ _google_and_new_tab](https://cloud.githubusercontent.com/assets/557895/13477980/a1f56c7e-e083-11e5-9353-b3167105e690.png)
**Figure 1:** "Activity Stream" button.

**Comment by rlr** [comment] 2016-03-29 16:25
@pdehaan Can you still reproduce this? I tried and it works as expected for me using your STR.

**Comment by pdehaan** [comment] 2016-03-29 17:29
@rlr: I can still repro via `$ npm run once`. Clicking the "Activity Stream" icon in browser window 2 opens the activity stream page in browser window 1.

**Comment by rlr** [comment] 2016-03-29 17:42
I can't repro with `npm run once` (which opens Firefox 46.0b1) either:

<img width="1275" alt="screen shot 2016-03-29 at 1 41 46 pm" src="https://cloud.githubusercontent.com/assets/36629/14117739/0a0fffdc-f5b4-11e5-83c4-49a29c653b70.png">

**Comment by rlr** [comment] 2016-03-29 17:46
We use `tabs.open()`. The docs say "Opens a new tab. The new tab will open in the active window or in a new window, depending on the inNewWindow option." https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/tabs#open(options)

**Comment by rlr** [comment] 2016-03-29 17:47
So the only way it would open in the wrong window is if it is somehow confused as to what the active window is.

**Comment by pdehaan** [comment] 2016-03-29 17:57
@rlr: I'll retest with a new profile and attempt to do a QuickTime screen recording after my meeting.

**Comment by pdehaan** [comment] 2016-03-29 18:53
![issue-253](https://cloud.githubusercontent.com/assets/557895/14119805/c87f039c-f5a4-11e5-9f5f-04b1aabcf831.gif)
**Figure 1:** 6MB GIF.

**Comment by rlr** [comment] 2016-03-29 18:55
yikes... ok.. i'll look to see if there is a different way of opening a tab and ensuring it's in the right window... Would be nice if I could repro... You are using new profile on beta?

**Comment by pdehaan** [comment] 2016-03-29 19:00
@rlr: Yep, just a git clone of this repo, and then `npm run once`. The "trick" seems to be launching the Activity Stream in window 1 before clicking the button in the second window.
Not sure how common this is, I just tripped over it one day and figured it must be due to some `target=_blank` thing.

Maybe we can try to get @k88hudson or @tspurway or @nchapman to test and be a tie breaker to see if it's just me with a weird browser/config.

**Comment by rlr** [comment] 2016-04-15 18:59
I am still unable to repro this using `npm run once`. Unassigning myself.

![screencast](https://cloud.githubusercontent.com/assets/36629/14572045/8e124588-031a-11e6-8520-024a7fc69f76.gif)

**Comment by sarracini** [comment] 2016-06-27 15:50
I can't reproduce this either... @pdehaan can you still?

**Comment by sarracini** [comment] 2016-10-17 17:52
Closing this since we've removed timeline

**Closed by sarracini** 2016-10-17 17:52 UTC
Labels: Bug, P3
