### ISSUE TITLE
Context menu doesn't work after sharing

### ISSUE THREAD

**Issue by ianb** [mozilla/activity-stream#1494] opened 2016-10-11 00:55 UTC
To reproduce:

1. Open the context menu on a highlighted item
2. Select Share > Twitter
3. Close the Twitter window
4. Attempt to open the context menu again.  Nothing happens, no error in the console.

If you open the context menu on a different tile then the first context menu starts working again.

Also happened with Tumblr (and other social options), but didn't happen with Open In New Window.

**Comment by SoftVision-CiprianMuresan** [comment] 2016-10-11 07:49
This is a dupe of #1372.

**Closed by SoftVision-CiprianMuresan** 2016-10-11 07:49 UTC
