### ISSUE TITLE
Handle experiment changes via prefs

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#1270] opened 2016-09-12 16:52 UTC
We need to add a way to be notified if the experiment status changes, as well as override them via prefs.

This ticket will remove the `overrideExperiments` pref with a new strategy:

-  all experiments are added dynamically by the experiment provider as separate prefs, each with an experiment prefix.
-  they will be exposed on `ExperimentProvider` with a getter, which simply looks at prefs.
- changes can listened to via `simplePrefs` (an interface for this could be added to ExperimentProvider for convenience)

**Comment by piatra** [comment] 2016-09-19 17:37
The deliverable of this bug is not clear to be.

**Comment by emtwo** [comment] 2016-10-17 17:02
dupe of #1511

**Closed by emtwo** 2016-10-17 17:02 UTC
Labels: P1
