### ISSUE TITLE
Clicking the pin icon does not unpin a topsite

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#3523] opened 2017-09-18 17:34 UTC
Firefox Version: 57.0a1 (2017-09-18) (64-bit)
OS Version: OSX 10.12.6

Steps to reproduce 

1) Click edit on topsites

2) Click the pin icon on a topsite

Expected results:

A topsite becomes unpinned, and the pin disappears next to its name

Actual results:

No change to the topsite

Attached screenrecording:

https://www.dropbox.com/s/linfrrob328215t/a-s%20pinned%20topsites.mov?dl=0

**Comment by rlr** [comment] 2017-09-18 17:38
Probably a duplicate of #3512

**Closed** 2017-09-18 18:03 UTC
