### ISSUE TITLE
Top sites skeleton UI appears broken after top sites upgrade (1.3.0-dev-1485385120)

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#2091] opened 2017-01-26 20:40 UTC
There should be outlined "skeleton" cards ☠️🃏 for the top sites. Possibly lost in the recent changes to top sites?

![screen shot 2017-01-26 at 2 36 23 pm](https://cloud.githubusercontent.com/assets/139451/22349391/1be8413c-e3d5-11e6-9fd3-124290ddac23.png)

**Comment by Softvision-VladBacia** [comment] 2017-01-27 10:35
This issue is also reproducible in Activity Stream Pre-release v1.3.0-pre-release-1485468410-8683703

**Comment by jaredkerim** [comment] 2017-01-30 19:28
This is a duplicate of #1841

**Comment by jaredkerim** [comment] 2017-01-30 19:36
This is not a duplicate of #1841 , it's missing the skeletons.  This is a bug.

**Closed** 2017-02-06 18:03 UTC
Labels: Has PR, MVP, P1, Regression
