### ISSUE TITLE
Dismissed or Deleted from History Top Sites/Highlights are displayed after page refresh

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#2078] opened 2017-01-25 17:04 UTC
**[Affected versions]:**
-Firefox 45.0 and up
-Activity Stream Pre-release 1.3.0-pre-release-1485308519-0fda037

**[Affected Platforms]:**
-All Windows
-All Mac OS X
-All Linux

**[Prerequisites]:**
-Latest Activity Stream Pre-release add-on version (1.3.0-pre-release) was previously installed on a profile.
-Have more history so that the "Highlights" area is populated with visited websites.
-From about:config, only the "extensions.@activity-streams.experiments.screenshots" experiment is set to true.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Hover on a Top Sites tile/Highlights tile and click on the "..." button.
3. Click on "Dismiss"/"Delete from History" option for the selected tile.
4. Refresh the AS New Tab page.
5. Observe the AS New Tab page.

**[Expected result]:**
-Dismissed or Deleted from History Top Sites/Highlights websites are no longer displayed after page refresh.

**[Actual result]:**
-Dismissed or Deleted from History Top Sites/Highlights websites are displayed after page refresh.

**[Notes]:**
- [Here](https://drive.google.com/open?id=0B6QogV2AJFKiRVhMdWMweUJvakU) is a video of the issue.
- Here is a screenshot with the AS active experiments:
![active experiments](https://cloud.githubusercontent.com/assets/9248513/22300454/290262da-e330-11e6-9109-d1e5cdfa5040.jpg)

**Comment by emtwo** [comment] 2017-01-30 19:44
Our unload reason being "refresh" occurs for less than 4% of sessions:

https://sql.telemetry.mozilla.org/queries/2449#4552

**Comment by bryanbell** [comment] 2017-03-10 18:16
![dismiss-fails](https://cloud.githubusercontent.com/assets/228979/23807435/830c14d0-057a-11e7-8f39-4028dbc2cb68.gif)

Confirming that this is still a problem, and it is a blocker.

**Comment by bryanbell** [comment] 2017-03-10 18:25
Seems that they do finally dismiss, but only after restart.

**Comment by sarracini** [comment] 2017-05-11 17:40
Can't reproduce this anymore - closing this until this is reported to happen again

**Closed by sarracini** 2017-05-11 17:40 UTC
Labels: Bug, MVP, P2, Regression

**Comment by Softvision-VladBacia** [comment] 2017-06-16 11:59
This issue has been verified on A-S 1.14.0-dev-1497551877-9d19af4 and I cannot reproduce is. Thus marking this as Verified-Fixed.
