### ISSUE TITLE
Remove a page from History on the Timeline Bookmarks tab

### ISSUE THREAD

**Issue by ciprianmuresan** [mozilla/activity-stream#584] opened 2016-04-27 12:24 UTC
I have observed a behavior, that in my opinion is wrong. On the Timeline, Bookmarks tab, if you remove a bookmark from History (by pressing X and choosing to remove from History) the page is removed from History and from the page you are in.  But after refreshing the Bookmarks page, the previously removed bookmark reappears in the list.

Wouldn't be better to have an option for removing from bookmarks instead from history since we are in Bookmarks page ? Or even both if we would like to offer also the possibility to remove the history related to that page. But even then I don't see why the bookmark is temporarily removed from the page when doing this and reappears after a refresh.

If we consider this a bug, we will log a correspondent in Bugzilla.

[Kazam_screencast_00007.mp4.zip](https://github.com/mozilla/activity-streams/files/238549/Kazam_screencast_00007.mp4.zip)

**Comment by tspurway** [comment] 2016-05-16 18:11
dupe of #659

**Closed by tspurway** 2016-05-16 18:11 UTC
