### ISSUE TITLE
Center the details page’s main content when possible

### ISSUE THREAD

**Issue by fvsch** [mozilla/activity-stream#692] opened 2016-05-12 20:58 UTC
I’m talking about the main content in the “All” and “Bookmarks” pages. Currently it’s left aligned.

When going from the New Tab view to this one on a screen at least 1300px wide, you end up with similar content that jumps visually (to the left). It might be nicer to have a more similar experience, with the main content being horizontally centered when there’s enough room.

By the way I mean centered in the viewport, not in its container. Quick test:

``` css
@media (min-width: 1240px) {
  main.timeline section.content {
    margin-left: 0;
  }
  main.timeline .wrapper {
    margin-left: auto;
    margin-right: auto;
  }
}
```

On 13" laptops it might be visual polish, but on wider screens the left alignment is really jarring.

PS: the `.wrapper`'s max-width seems a bit off. 688px but top content is roughly 700px.

**Comment by bryanbell** [comment] 2016-05-24 15:26
I see you're point for sure. Part of the rationale for the left alignment is that we're planning to marry this type of sidebar UI with other sidebar UI's in the product already, like Settings for instance. Adding navigation that lets you move back and forth between these full screen UI's. 

Also in the future what's on the New Tab page and the activity stream will diverge a bit. The New Tab might sown you a more curated collection of items in the near future, not simply the top of all recent activity. 

I'll explore options that mitigate this shift on wide screens.

**Comment by sarracini** [comment] 2017-01-17 22:26
Dupe of #1276

**Closed by sarracini** 2017-01-17 22:26 UTC
Labels: Feature request, P3
