### ISSUE TITLE
Text below top sites is vertically misaligned

### ISSUE THREAD

**Issue by jbuck** [mozilla/activity-stream#2439] opened 2017-04-18 19:14 UTC
![screenshot 2017-04-18 15 10 43](https://cloud.githubusercontent.com/assets/578466/25148525/385e096e-2449-11e7-951a-4e5a44ecbcd8.png)

Affected version: Activity Stream 1.9.0 from Test Pilot

The text for twitter, hacker news, and aws console is aligned vertically higher than the other top sites. The overflowing text for YNAB also doesn't get the ellipsis treatment like the others do. I think it's related to whether or not the favicon is displayed in the top left corner of a top site or not.

**Comment by tspurway** [comment] 2017-04-18 21:16
I am seeing some topsite misalignment as well, both in release and dev channels (1.9, 1.10dev) on a Windows 8.1 laptop.

![ascapture](https://cloud.githubusercontent.com/assets/25276/25153504/c44f2834-245a-11e7-9020-e9b985249a9e.PNG)

**Comment by rlr** [comment] 2017-04-18 21:21
"awesome"

@jbuck are you on Windows too?

It all lines up perfectly for me on OS-X 😆

**Comment by jbuck** [comment] 2017-04-18 21:45
I'm using Firefox Stable 52.0.2 on macOS 10.12.4

I just had a look in the inspector, and the top sites with the favicon had the css class `site-title` applied to the text, and the top sites without the favicon had the css class `site-icon-title` applied. That's why there's more margin on the top sites with the favicon

**Comment by rlr** [comment] 2017-04-18 21:49
Ah, @jbuck's issue is fixed on dev channel (https://moz-activity-streams-dev.s3.amazonaws.com/dist/latest.html)

But @tspurway's looks like it might be an issue on Windows (or non OS-X)

**Comment by jaredkerim** [comment] 2017-04-24 18:37
Close this as a duplicate of #2447

**Closed by jaredkerim** 2017-04-24 18:37 UTC
