### ISSUE TITLE
default topsites don't have images if yarn used instead of npm

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#1683] opened 2016-11-01 17:32 UTC
Steps to reproduce:

In separate terminals: 
* ```npm run start```
* ```npm run firefox```

Then:
* Open a new tab

![screen shot 2016-11-01 at 10 30 07](https://cloud.githubusercontent.com/assets/425657/19899699/43835ab0-a01e-11e6-85a3-bc51898e3187.png)

The images for the top sites should be supplied by tippy-top-sites, I believe.

Seems like we should be able to implement a simple integration test that prevents this sort of regression just by looking at the metadata on the default sites without having to paint anything.

**Comment by jaredkerim** [comment] 2016-11-01 17:41
@dmose I think we should definitely think about setting up some quality preserving regression tests for things like this because I've seen a few regressions of that type recently.  I'm not able to reproduce this on master using `npm start firefox`.  Can anyone else reproduce this?

**Comment by k88hudson** [comment] 2016-11-01 17:44
I'm pretty sure this is for old highlights only

**Comment by dmose** [comment] 2016-11-01 17:51
@jaredkerim suppose you "npm run clean &&& rm -fr node_modules" and then reinstall it with the latest yarn?  Do you see it then?

**Comment by dmose** [comment] 2016-11-01 17:52
Homebrew also recently updated my node to 7.0.0, which could also be relevant...

**Comment by sarracini** [comment] 2016-11-01 18:10
@dmose i can't reproduce even with npm run clean and re-installing all the new node modules

**Comment by dmose** [comment] 2016-11-01 18:18
@sarracini @jaredkerim what versions of node are you running?

**Comment by sarracini** [comment] 2016-11-01 18:19
@dmose i'm on 6.2.1

**Comment by pdehaan** [comment] 2016-11-01 18:24
I can't reproduce w/ Nightly + 76c91c401309370383134d7507378ef7e045f03a (via `git rev-parse --short HEAD`) + `npm run once`:

```js
$ npm version

{ 'activity-streams': '1.1.5',
  npm: '3.10.8',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.9.0',
  openssl: '1.0.2j',
  uv: '1.9.1',
  v8: '5.1.281.84',
  zlib: '1.2.8' }
```

---

![new_tab](https://cloud.githubusercontent.com/assets/557895/19901597/d342ab5a-a024-11e6-875f-5e2756fb0848.png)

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/19901614/e7544a4a-a024-11e6-87b3-a26f2cdf59b8.png)

![about_config](https://cloud.githubusercontent.com/assets/557895/19901814/a706c192-a025-11e6-9235-bf335b8b5d9c.png)

![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/19901601/d8505746-a024-11e6-9306-b9c373e7bd88.png)

**Comment by pdehaan** [comment] 2016-11-01 18:37
> Homebrew also recently updated my node to 7.0.0, which could also be relevant...

FWIW, you should be using [nvm](https://github.com/creationix/nvm) to juggle Node versions. Much nicer.

**Comment by dmose** [comment] 2016-11-01 18:41
Medal goes to @sarracini, installing with npm makes the problem go away.

**Comment by sarracini** [comment] 2017-01-17 21:47
Closing this since we've decided it's a wontfix

**Closed by sarracini** 2017-01-17 21:47 UTC
Labels: Chore, P3
