### ISSUE TITLE
Installed but doesn't replace about:newtab?

### ISSUE THREAD

**Issue by FoxXT** [mozilla/activity-stream#733] opened 2016-05-19 21:30 UTC
OS: Ubuntu 16.04
Firefox: FF v46.0.1

**Comment by softvision-VladBacia** [comment] 2016-05-20 07:31
@FoxXT, thank you for reporting this. This issue is already in discussion. For more information, see #724 .

Closing as dupe of #724 .

**Closed by softvision-VladBacia** 2016-05-20 07:31 UTC
