### ISSUE TITLE
Dotted focus-outline on Activity Stream "Highlights" runs through the "Visited N minutes ago" annotation

### ISSUE THREAD

**Issue by dholbert** [mozilla/activity-stream#677] opened 2016-05-11 18:54 UTC
STR:
 1. Activate Activity Stream.
 2. Press Tab until one of your Highlights is focused.
   ...OR: Click and drag one of your Highlights a few pixels away from its normal spot. (This leaves it with a dotted focus rect).

ACTUAL RESULTS:
 The dotted focus rect ends up striking through the "Visited N minutes ago" annotation below.

EXPECTED RESULT:
 The dotted focus rect should surround that annotation.

**Comment by dholbert** [comment] 2016-05-11 18:56
This happens because the "Visited N minutes ago" text is absolutely positioned -- which means it doesn't get grouped into the bounding-box of its `<a>` link ancestor.

**Comment by dholbert** [comment] 2016-05-11 19:00
I don't think there's a good reason for this text to be absolutely positioned...

If I drop its `position:absolute` styling, and simplify its `padding: 12px` to `padding-top: 12px`, then it looks almost the same as its current rendering, and this bug becomes fixed.

**Comment by dholbert** [comment] 2016-05-11 19:03
Here's a screenshot of the bug, after performing the STR:
![Screenshot of the bug](https://cloud.githubusercontent.com/assets/426803/15192894/22f9c22a-1770-11e6-829a-2bce61a3be23.png)

Here's a screenshot of what this looks like after I make the tweaks that I noted above (dropping `position:absolute` and only applying `padding` on top), as an example "reference" rendering:
![Screenshot of expected rendering](https://cloud.githubusercontent.com/assets/426803/15192935/5df6c616-1770-11e6-871c-eec8a9faf946.png)

**Comment by SoftVision-PaulOiegas** [comment] 2016-05-12 07:52
This is a duplicate of 673, that is already logged in Bugzilla too

**Comment by tspurway** [comment] 2016-05-16 17:35
dupe #673

**Closed by tspurway** 2016-05-16 17:35 UTC
Labels: Add-on UI, Good first bug, Polish
