### ISSUE TITLE
Make it easy to enable an experiment locally

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-stream#950] opened 2016-07-22 18:24 UTC
a few people have asked to see the recommendations feature, it would be great to be able to turn on an experiment locally.  Maybe edit a pref file or about:config flag

**Comment by pdehaan** [comment] 2016-07-22 18:32
big :+1: from the QA side. It'd be really nice to be able to have a hidden flag or something obscure so we can override experiment opt-in so we can guarantee that we're included in experiments.

**Comment by jaredkerim** [comment] 2016-07-25 19:10
This is a duplicate of #964

**Closed by jaredkerim** 2016-07-25 19:10 UTC
Labels: P1
