### ISSUE TITLE
[Search bar] A different keyword is searched for when using a different search engine

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#1884] opened 2016-12-20 13:17 UTC
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1385841
[Notes]:
- If a suggested keyword is highlighted in the Search Suggestions dropdown, the search will be made for **that** keyword and not the one written in the Search bar. 
- The only way to avoid this is to move the mouse around the suggestions (outside the dropdown) and then click one of the Search Engines.

[Affected versions]:
- Nightly 53.0a1
- Activity Stream 1.1.8-prerelease

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.1.8-prerelease) was previously installed on a clean profile.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites.
2. Open a new tab and write something in the AS search bar.
3. Mouseover the search sugestions to reach the Search Engine selection area on the bottom.
4. Click one of the Search Engine icons.
5. Observe the searched keyword.

[Expected results]:
- The searched keyword is the same with the manually entered one.

[Actual results]:
- The searched keyword wrongly becomes the highlighted one.

[Additional Notes]:
- The issue is also reproducible on the Activity Stream Dev version of the add-on.
- Attached a screenshot of the issue.
![an incorrect keyword is being searched](https://cloud.githubusercontent.com/assets/18304511/21351174/d58bd858-c6c3-11e6-848c-41435608ea0f.gif)

**Comment by sarracini** [comment] 2017-06-28 17:29
Closing this since we're re-using the search from about:newtab and about:home, and so we get the same behaviour as they have

**Comment by Softvision-VladBacia** [comment] 2017-07-31 11:03
Filed a Bugzilla issue https://bugzilla.mozilla.org/show_bug.cgi?id=1385841 . Reopening this for tracking purposes.

**Comment by sarracini** [comment] 2018-01-11 19:21
closing this - no longer reproducible on latest nightly and bugzilla bug marked resolved

**Closed by sarracini** 2018-01-11 19:21 UTC
Labels: Bugzilla, P4
