### ISSUE TITLE
Locale/Location specific Top Sites?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#3050] opened 2017-08-01 04:52 UTC
I live in Canada. I should see amazon.ca, ebay.ca, yahoo.ca, etc.

Not sure if we just start some big matrix of countries and any location specific top sites overrides. That would imply that we try looking up a user's location somehow, which may be weird. But maybe not as weird as showing me a link to a US Amazon.com site.

**Comment by Mardak** [comment] 2017-08-01 04:54
Dupe of #2776 which has PR #3022 waiting on final confirmation of top sites for desired countries/regions.

**Closed by Mardak** 2017-08-01 04:54 UTC
