### ISSUE TITLE
Mozilla Central implement about:home metrics tag

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#2001] opened 2017-01-18 18:30 UTC
Split from #1974. We need a way to distinguish between about:home and about:newtab in every one of our telemetry pings.

**Comment by k88hudson** [comment] 2017-05-15 17:18
This is a dupe of https://github.com/mozilla/activity-stream/issues/2510

**Closed by k88hudson** 2017-05-15 17:18 UTC
Labels: Graduation, MVP, Parity
