### ISSUE TITLE
Add better multi-line ellipsis based on character count  (Bug 1262435)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#502] opened 2016-04-12 17:46 UTC
Bug 1262435 - Long titles are incorrectly truncated in "Highlights" section from "Timeline" and "New Tab"
via https://bugzilla.mozilla.org/show_bug.cgi?id=1262435

---

Created attachment 8738545 [details]
screenshot of the issue.PNG
![image](https://cloud.githubusercontent.com/assets/1455535/14470191/f3bb6fca-009c-11e6-92bc-4c3b71758177.png)
#### [Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.7
#### [Affected Platforms]:
- Windows XP
#### [Prerequisites]:
- It will be best to use a clean profile.
- Latest Activity Stream add-on version (1.0.7) was previously installed on the used profile.
#### [Steps to reproduce]:
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Open a new tab and visit a page that has a long title (ex: http://goo.gl/EpguE8). 
3. Click on "Activity Stream" button from browser toolbar (if the website is not displayed in the Highlights from first try please refresh the page). 
4. Observe the title of the page in the "Highlights" area.
#### [Expected results]:

The title is correctly truncated when it exceeds the designed area.
#### [Actual results]:

The title is incorrectly truncated when it exceeds the designed area.
#### [Notes]:
- This issue is reproducible also in New Tab page.
- I've attached a screenshot of the issue.

**Comment by CosminMuntean** [comment] 2016-05-19 13:56
I have tested again this issue on Windows XP, on the latest Nightly (49.0a1) build with Activity Stream addon v1.0.17 and is still reproducible.
![screenshot of the issue](https://cloud.githubusercontent.com/assets/19226534/15395958/94a33abe-1de2-11e6-8889-0824010c3ac3.PNG)

**Comment by sarracini** [comment] 2016-06-21 13:57
@SoftVision-VladBacia I can't reproduce this anymore, can you confirm?

**Comment by SoftVision-VladBacia** [comment] 2016-06-21 15:03
This issue has been verified on Win XP x86 with latest Nightly 50.0a1 (Build ID: 20160621030208) using latest Activity Stream v1.1.0-custom build and could reproduce it. On other systems, we didn't encounter this issue.
![long titles](https://cloud.githubusercontent.com/assets/9248513/16234292/b50e42f6-37d9-11e6-813a-32cba45c7086.PNG)

**Comment by k88hudson** [comment] 2016-07-26 19:08
Also could be done in this ticket: add middle ellipsis to context messages e.g. "Synced from Katherine Hudson's iPhone" would get shorted to "Synced from Ka... iPhone"

**Comment by dmose** [comment] 2016-10-13 16:25
The ellipsis part of this often times referred to as "line clamping".  There are lots of hacky, edge-casey solutions floating around npm and various blogs. https://bugzilla.mozilla.org/show_bug.cgi?id=1232992 is the browser bug for the CSS max-lines property, which is what we _really_ want.  That said, chances are good that we'll need to choose one of the hacks to fix this one.  A particularly interesting part is going to be finding one that handles both LTR and RTL languages, which is likely to be required to get it into m-c.

**Comment by sarracini** [comment] 2017-01-17 22:27
Closing this as a dupe of #1971

**Closed by sarracini** 2017-01-17 22:27 UTC
Labels: Bugzilla, P3, Polish
