### ISSUE TITLE
Keystrokes Lost in Search Bar

### ISSUE THREAD

**Issue by kdoske** [mozilla/activity-stream#848] opened 2016-06-14 03:58 UTC
As I type random keystrokes appear to be instantly backspacing on there own and my next key stroke overwrites the previous letter. Its not every key stroke but probably ever 3rd one or so. I had to turn it off. It was driving me mad.

**Comment by sarracini** [comment] 2016-06-20 15:06
I don't actually know if this can be fixed...it can be a result of a lot of things but most likely because message passing from content to addon happens when the a new key stroke happens and it needs to fetch the new suggestions - if it's slow this might be a result of that.
Not sure how we can fix that

**Comment by wlusink** [comment] 2016-06-20 15:30
Right now I think I can see that the suggestion code is re-writing the contents of the text box? I don't see why it should do that. If I am just typing a character in that instance, my character is overwritten with the older value from the suggestion code.

I think the suggestion-code should never write anything in the textbox. It should only read.

**Comment by rlr** [comment] 2016-06-24 19:04
fixed via pull #879

**Closed** 2016-06-24 19:05 UTC
Labels: Bug, Polish, Search

**Comment by SoftVision-VladBacia** [comment] 2016-06-27 11:32
This issue has been verified on Win 8.1 x64, Mac OS X 10.11 and Ubuntu 14.04 x64 with latest Nightly 50.0a1 (Build ID: 20160626030213) using latest Activity Stream v1.1.0-custom build and could not reproduce it. The fix will be available in the next release.
Thus, marking this issue as Verified-Fixed.
