### ISSUE TITLE
AS Crashes

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#1451] opened 2016-10-04 20:19 UTC
I am running Firefox 50.0b2 on OSX 10.11.6

`NS_BINDING_ABORTED: Component returned failure code: 0x804b0002 (NS_BINDING_ABORTED) [nsIStreamListener.onDataAvailable]WebRequest.jsm:227
MetadataStore failed to insert metadata: Error(s) encountered during statement execution: UNIQUE constraint failed: page_metadata.cache_keyMetadataStore.js:284
Error: Error(s) encountered during statement execution: UNIQUE constraint failed: page_metadata.cache_key
Stack trace:
ConnectionData.prototype<._executeStatement/pending<.handleCompletion@resource://gre/modules/Sqlite.jsm:807:25
iu@file:///Users/tspurway/Library/Application%20Support/Firefox/Profiles/doj1odpo.default/extensions/support@lastpass.com/components/lastpass.js:140:340
_doButtonCommand@chrome://global/content/bindings/notification.xml:461:30
oncommand@chrome://browser/content/browser.xul:1:1
Sqlite.jsm:648
MetadataStore failed to insert metadata: Error(s) encountered during statement execution: UNIQUE constraint failed: page_metadata.cache_keyMetadataStore.js:284
Error: Error(s) encountered during statement execution: UNIQUE constraint failed: page_metadata.cache_key
Stack trace:
ConnectionData.prototype<._executeStatement/pending<.handleCompletion@resource://gre/modules/Sqlite.jsm:807:25
iu@file:///Users/tspurway/Library/Application%20Support/Firefox/Profiles/doj1odpo.default/extensions/support@lastpass.com/components/lastpass.js:140:340
_doButtonCommand@chrome://global/content/bindings/notification.xml:461:30
oncommand@chrome://browser/content/browser.xul:1:1
Sqlite.jsm:648
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise
Date: Tue Oct 04 2016 14:08:24 GMT-0400 (EDT)
Full Message: Error: Error(s) encountered during statement execution: UNIQUE constraint failed: page_metadata.cache_key
Full Stack: ConnectionData.prototype<._executeStatement/pending<.handleCompletion@resource://gre/modules/Sqlite.jsm:807:25
iu@file:///Users/tspurway/Library/Application%20Support/Firefox/Profiles/doj1odpo.default/extensions/support@lastpass.com/components/lastpass.js:140:340
_doButtonCommand@chrome://global/content/bindings/notification.xml:461:30
oncommand@chrome://browser/content/browser.xul:1:1
Sqlite.jsm:807
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise
Date: Tue Oct 04 2016 14:08:27 GMT-0400 (EDT)
Full Message: Error: Error(s) encountered during statement execution: UNIQUE constraint failed: page_metadata.cache_key
Full Stack: ConnectionData.prototype<._executeStatement/pending<.handleCompletion@resource://gre/modules/Sqlite.jsm:807:25
iu@file:///Users/tspurway/Library/Application%20Support/Firefox/Profiles/doj1odpo.default/extensions/support@lastpass.com/components/lastpass.js:140:340
_doButtonCommand@chrome://global/content/bindings/notification.xml:461:30
oncommand@chrome://browser/content/browser.xul:1:1
Sqlite.jsm:807
TypeError: can't access dead objectlastpass.js:1677:263
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src resource://activity-streams”).activity-streams.html:1
TypeError: this.controller is undefined[Learn More]`

**Comment by ncloudioj** [comment] 2016-10-06 19:37
I guess this has to do with the transaction "delay" issue with `sqlite.jsm`. The last transaction "allegedly" gets committed, but the change of that transaction isn't synced to the disk.

Will make a fix for this.

**Comment by dmose** [comment] 2016-10-10 20:29
I have a local build from master that has the above fix (#1451) from Friday.  Executing "npm run once" It hangs in the same visual one ("Hang on tight"), the console has (effectively) the same error:

```
13:23:51.335 MetadataStore failed to insert metadata: Error(s) encountered during statement execution: UNIQUE constraint failed: page_metadata.cache_key 1 MetadataStore.js:284
	MetadataStore.prototype.asyncInsert</< resource://activity-streams/addon/MetadataStore.js:284:11
	throw self-hosted
	TaskImpl_run resource://gre/modules/Task.jsm:323:42
	bound TaskImpl_run self-hosted
13:23:51.337 Error: Error(s) encountered during statement execution: UNIQUE constraint failed: page_metadata.cache_key
Stack trace:
ConnectionData.prototype<._executeStatement/pending<.handleCompletion@resource://gre/modules/Sqlite.jsm:807:251 Sqlite.jsm:648
13:23:51.338 Error(s) encountered during statement execution: UNIQUE constraint failed: page_metadata.cache_key 1 Sqlite.jsm:807
	ConnectionData.prototype<._executeStatement/pending<.handleCompletion resource://gre/modules/Sqlite.jsm:807:25
```

So while the promise may now be caught, we still end up in the same state.  If I'm understanding correctly, it looks like there are two problems:

* we should not be hitting the UNIQUE constraint at all
* somehow, catching the promise isn't sufficient to cause the new tab page to render

**Comment by dmose** [comment] 2016-10-10 20:30
At this moment, my tree is on commit f3448b9490ba447baf658bc287dffd0071a2c02e

**Comment by dmose** [comment] 2016-10-10 20:50
Intriguingly, updating my tree to ad3ca50229bd08399788815e47cd485c160de141 , doing 

```
npm run clean
npm install && npm run once
```

has generated a couple of runs without this problem.

Hmmm.

**Comment by dmose** [comment] 2016-10-10 20:51
(And the only interesting changes there are to package.json)

**Comment by dmose** [comment] 2016-10-10 20:54
It is at least possible that there was some build problem that hadn't picked up Nan's change, and the "npm run clean" was what did the trick.

**Comment by dmose** [comment] 2016-10-11 03:57
OK, I've seen this once again on latest master after doing another clean, so I think the problems are indeed still here.

**Comment by ncloudioj** [comment] 2016-10-11 13:26
hmm, interesting. I couldn't reproduce this failure here, and it's quite strange to see this happening with a new user profile. @sarracini did we change anything regarding `cache_key` generation and metadata persistence in the `PreviewProvider.js`?

**Comment by ncloudioj** [comment] 2016-10-14 19:09
Close #1451 via 3bb9c71427e78742a0d9443c95b020b36e9ca4ae

**Closed by ncloudioj** 2016-10-14 19:09 UTC
Labels: Bug, in progress, P1

**Comment by k88hudson** [comment] 2016-10-14 22:42
\o/
