### ISSUE TITLE
A-S hits a "TypeError" when Nightly reboots from an upgrade

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#2929] opened 2017-07-21 14:32 UTC
Nightly (56.0a1) on Mac OS X

This ended up with a blank page when opening a newtab with A-S system addon. 

<img width="959" alt="screen shot 2017-07-21 at 10 26 19 am" src="https://user-images.githubusercontent.com/1455254/28467956-8799b118-6dff-11e7-8c91-f7ca19c51251.png">

**Comment by Mardak** [comment] 2017-07-21 14:56
Dupe of #2819

**Closed by Mardak** 2017-07-21 14:56 UTC
Labels: MVP
