### ISSUE TITLE
Hang Tight refresh should not cause a new telemetry session

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1869] opened 2016-12-13 22:39 UTC
If a user opens a new tab, it brings up the 'Hang Tight' screen which attempts to refresh the page every 3 seconds but it never breaks out of the 'Hang Tight' loop (which we've seen is still happening) then it will cause a session telemetry ping each time it tries to refresh the page, every 3 seconds.  This can break our telemetry analysis by heavily skewing the number of sessions we see.  We shouldn't fire a new session telemetry ping every time hang tight tries to refresh the page.

**Comment by Mardak** [comment] 2016-12-14 11:39
@dmose I thought the rehydration avoided the page refresh, so there wouldn't be multiple telemetry pings?

**Comment by dmose** [comment] 2016-12-14 17:36
The rehydration does avoid the page refresh, but it replaces it with a MERGE_STORE action, which merges the rehydrated state with whatever is already in the store.  I'd guess something in the changed state is what's causing the telemetry to re-ping.  Perhaps looking at the action logger output to the console will give some indication as to why...

**Comment by dmose** [comment] 2016-12-14 17:37
Or even using the redux dev-tools...

**Comment by dmose** [comment] 2016-12-20 01:28
@jaredkerim @emtwo I've been unable to reproduce this after a fair amount of playing around, commenting stuff out, etc.  It's very easy for me to imagine how this would have happened before https://github.com/mozilla/activity-stream/commit/df7f9f65d6c3a0fa8f372a4859a694331640c702 landed (Nov 8th), and I don't see how it would be happening after that.

Is it possible to tell what versions these pings are coming from?  In particular, I'd love to know the newest version that is seeing this...

**Comment by dmose** [comment] 2016-12-20 01:32
Poking around a bit more, neither 1.1.7 nor 1.1.8 have the commit mentioned above, so it's unsurprising this error is happening in the wild.  It seems like release latency is somehow biting us here...

**Comment by dmose** [comment] 2016-12-20 02:50
This is really a duplicate of #1767; resolving.

**Closed** 2016-12-20 02:50 UTC
Labels: P1
