### ISSUE TITLE
Highlights - Icons

### ISSUE THREAD

**Issue by AdamDenoon** [mozilla/activity-stream#727] opened 2016-05-19 15:20 UTC
In the thumbnails for the highlights, there is an empty grey box, with a very pixelated favicon in the upper-left. The aesthetics don't look good.

OSX 10.11.4
Firefox 46.0.1

**Comment by AdamDenoon** [comment] 2016-05-19 15:26
This issue seems to have resolved itself. So these sites took time to generate proper previews, for some reason.

**Comment by pdehaan** [comment] 2016-05-19 20:11
@AdamDenoon Thanks for the bug report!
Yes, in certain circumstances (ie: first request) the thumbnails may take a bit of time for us to fetch and cache, so you may see an empty grey box.

The pixelated favicon is a separate issue that we're working on, but currently [I believe] we're just using the favicon.ico returned by the remote server. For some more information, see #603.

Closing as dupe of #603.

**Closed by pdehaan** 2016-05-19 20:11 UTC
