### ISSUE TITLE
Bug 1289788 - The "Trending Highlight" tile is not displayed on 3rd position in "Timeline" page

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#977] opened 2016-07-27 14:19 UTC
via https://bugzilla.mozilla.org/show_bug.cgi?id=1289788
<br>
[Affected versions]:
- Firefox 45 and up
- Activity Stream 1.1.1-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- A new Firefox profile was previously created.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Install the latest version of AS add-on (1.1.1-dev).
3. Open a new tab and observe the "Trending Highlight" tile position.
5. Open the "Timeline" page and observe the "Trending" article position.

[Expected result]:
- The article is displayed in the 3rd "Highlights" tile on both pages.

[Actual result]:
- The article is wrongly displayed on "Timeline" page in the 1st "Highlights" tile.

[Notes]:
- Managed to have it displayed also on 2nd highlight position on a profile with history and bookmarks stored.
- Bookmarking the "Trending" article will always move it on first position in "Timeline" page.
- Reproducible 5/5.
- A screen recording describing the issue was attached https://goo.gl/TLU7ur.

**Comment by sarracini** [comment] 2016-07-27 15:56
Closing this as a dupe of #955

**Closed by sarracini** 2016-07-27 15:56 UTC
