### ISSUE TITLE
Settings button is overlapping in activity stream newtab when settings has scrollbar

### ISSUE THREAD

**Issue by Tanvir-rahman** [mozilla/activity-stream#3931] opened 2018-01-12 19:04 UTC
#### Expected behavior
There should be some margins in right side of the button

#### Actual behavior
There are no margins in right side of the button

#### How to reproduce
1) Download the specific build.
1) Start Firefox with clean profile.
2) Open new Tab and click settings button ( See Attached Screenshot).

* Browser:  Firefox
* Operating system: Windows 10
* User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
* Build ID: 20171112125346

#### Recording Of The Bug
![Bug.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1515739096/w5lxdvajvlx3gs9nf4yb.png)
   

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@tanvirrahman/settings-button-is-overlapping-in-activity-stream-newtab-when-settings-has-scrollbar">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Mardak** [comment] 2018-01-12 22:25
Dupe of #2789

**Closed by Mardak** 2018-01-12 22:25 UTC
