### ISSUE TITLE
Duplicate highlights

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1788] opened 2016-11-11 21:37 UTC
<img width="747" alt="screenshot 2016-11-11 16 09 10" src="https://cloud.githubusercontent.com/assets/119884/20230316/51a30d76-a829-11e6-8dbc-b1d7541c370b.png">

Initially I had all unique highlights, and then I dismissed the bottom right one, and the duplicate entered.  It disappeared after I opened a new tab, so I think this case tries to sort itself out, I wasn't able to recreate it when I tried.

**Comment by jaredkerim** [comment] 2016-11-11 21:38
Oh! I think it's the same article but with two different URLs, ie the different favicons.  One thing we've discussed in the past is deduping weighted highlights on image path instead of URL, perhaps that's still something we want to consider?

**Comment by pdehaan** [comment] 2016-11-11 21:50
Yeah, if you can find those links again, I'm curious what they are.

I think BBC is just a big mess of hurt, due to their aggressive [mis]redirection betwixt their .co.uk and .com TLDs. So my guess is that you tried looking at a bbc.co.uk URL and they detected that you were not in the UK and you got put back into a .com flow.
But that's just a guess based on some old BBCin I've done in the past.

**Comment by tspurway** [comment] 2017-04-19 18:28
can't reproduce any longer.  closing

**Closed by tspurway** 2017-04-19 18:28 UTC
Labels: Design feedback needed, MVP, P2
