### ISSUE TITLE
No Activity Stream icon/button installed

### ISSUE THREAD

**Issue by fburleigh** [mozilla/activity-stream#1899] opened 2016-12-24 16:04 UTC
Your messaging shows an icon for the add-on that looks like a graph. I believe that icon opens a timeline. Installing Test Pilot and then AS to Fx 53 on macOS and to Fx 50 on Windows 10 includes Test Pilot's icon, but not one for Activity Stream itself. 

I was just prompted to do a survey about AS.  It showed elements of AS that I don't have.

The icon is also not available among the customize options.

**Comment by Softvision-VladBacia** [comment] 2017-01-03 16:35
@fburleigh thank you for reporting this. 

The issue is related to #1544 :) . Activity Stream page needs to be updated in Test Pilot to reflect latest changes for the experiment.

**Comment by purpleyuan** [comment] 2017-01-03 17:52
Is this at all related to #1802 and #1889? I've been following these for a while since I've been having the same issues.

**Comment by jaredkerim** [comment] 2017-01-03 19:24
That icon has been removed, we need to update the screenshots, closing as a duplicate of:

https://github.com/mozilla/activity-stream/issues/1544

**Closed by jaredkerim** 2017-01-03 19:24 UTC
