### ISSUE TITLE
Activity Stream loading delay is jarring

### ISSUE THREAD

**Issue by theres-waldo** [mozilla/activity-stream#684] opened 2016-05-12 00:05 UTC
Often the following happens:

1. I open a New Tab
2. I type something into the URL bar or search bar and press enter
3. Activity Stream loads
4. My page or search results load, replacing Activity Stream

Whenever (3) happens after (2) - which is fairly often - it feels like (3) is the _response_ to (2), which is unexpected.

I would suggest that, if Activity Stream hasn't loaded by the time I pressed <enter> in the URL or search bar (or maybe even after I started typing there?), that it doesn't load at all.

**Comment by softvision-VladBacia** [comment] 2016-05-12 15:24
@theres-waldo , I cannot reproduce the issue that you've reported.
I've tried the scenario with a new profile, with an old profile that has a lot of history, and also simulated low bandwidth conditions. I have opened the New Tab page and before the content loaded I've performed a search through URL bar, search bar, New Tab search bar. Each time the page of search results has correctly replaced the Activity Stream New Tab page.

The test were performed on Windows 8.1 x64 with latest Firefox (46.0.1, Build ID: 20160502172042) and latest Nightly (49.0a1, Build ID: 20160512030253).
Please provide more details regarding the system that you use, Firefox version, if you use a new profile or an old one, and it would be very helpful if you could post a video of the issue. 
Thank you.

**Comment by theres-waldo** [comment] 2016-05-12 16:26
> Each time the page of search results has correctly replaced the Activity Stream New Tab page.

I'm not saying the search results page doesn't replace the Activity Stream New Tab page - it does.

I'm saying the Activity Stream New Tab page appears so late, I've already entered my search query and pressed enter. (The search results page appears subsequently.) As a result, it seems like the Activity Stream page is appearing in response to my search query, which feels strange.

**Comment by pdehaan** [comment] 2016-05-12 16:53
@theres-waldo: Is Activity Stream slow _every_ time you open a new tab, or was it just the _first_ time?

Unfortunately, it does take a bit of time to fetch your local history, do some de-duping, grab favicons, etc. &mdash; so the first time you use Activity Stream it may take a few seconds for all the data to flow in and be cached. Future usage should be much faster. 

But the "Activity Stream page is appearing in response to my search query" seems very unrelated and probably just a random timing coincidence.

**Comment by theres-waldo** [comment] 2016-05-12 17:07
> @theres-waldo: Is Activity Stream slow every time you open a new tab, or was it just the first time?

I definitely notice the delay every time. Whether it's so long that I finish typing a query before it appears, varies, but it's definitely not limited to the first time.

Note that I made a specific suggestion in my original report: if I've hit <enter> in the URL or search bar, and Activity Stream hasn't shown up yet, don't bother showing it at that point, just keep the screen blank until my page or search results load.

**Comment by pdehaan** [comment] 2016-05-12 17:37
> Note that I made a specific suggestion in my original report: if I've hit in the URL or search bar, and Activity Stream hasn't shown up yet, don't bother showing it at that point, just keep the screen blank until my page or search results load.

Yeah, I was still trying to mentally picture that. It sounds like it could be slightly terrifying in darker edge cases.

Your use case sounds valid. You're signaling the intent to go to a specific URL and you're done w/ Activity Stream, so we can probably just abort your in-flight request.

The alternate use case (that concerns me) is if the user clicks in the address bar and types something (or not) but doesn't submit the search/URL and goes back to the page. Depending on how we handle that, we may have aborted their in-flight requests and then left them with a blank page that would never show anything.

Thankfully I'm just a QA, so I can let other people solve all the hard problems and then sit back and tell them they did it wrong. We'll discuss this issue in our next bug triage meeting and I can update the bug with any information. 🍻

**Comment by marco-c** [comment] 2016-05-18 12:25
I think the problem is generic and not only related to searching. Opening a new tab with activity stream is noticeably slower than opening a new about:newtab tab.

**Comment by theres-waldo** [comment] 2016-06-03 17:25
FWIW, in recent nightlies, the loading of the activity stream feels more snappy, and as a result this has been bothering me less.

**Comment by sarracini** [comment] 2016-06-20 20:22
Closing this on account of Activity Stream having much better performing as of late 👍

**Closed by sarracini** 2016-06-20 20:22 UTC
Labels: Performance

**Comment by marco-c** [comment] 2016-06-20 20:51
It's still quite slow for me, compared to about:newtab. I'm not sure you can reach the same level of performance, but it certainly feels like there's still room for improvement.

**Comment by ncloudioj** [comment] 2016-06-20 20:59
True, we've seen some performance drops in the most recent release. Filed #868 to track this issue again.
