### ISSUE TITLE
"from pocket" logo is clipped

### ISSUE THREAD

**Issue by dholbert** [mozilla/activity-stream#2727] opened 2017-06-15 17:01 UTC
In my Linux Nightly with Activity Stream enabled, the ""from pocket" logo (to the right of "Top Stories") is clipped.  Specifically:

 - the descending line from "p" is covered up (so it looks like like "oocket")
 - the bottom of the circle-"?" logo is clipped/flattened

**Comment by dholbert** [comment] 2017-06-15 17:03
![Screenshot](https://user-images.githubusercontent.com/426803/27192913-e63fbd8a-51b1-11e7-8ec1-1bc85c3f2d23.png)

**Comment by dholbert** [comment] 2017-06-15 17:19
This element's sizing is a bit complicated:
 * it's a `<span>`
 * The logo is a `background-image` with a specific `background-size`
 * ...but the `span`'s height has nothing to do with that background-size, so if the span is shorter, then the background image gets clipped.

The `span` gets its height from the "font-size" that it inherits (and what height that actually translates to, for the font that we actually use there).  Given this fragile font-sizing dependency, I wouldn't be surprised if this is broken on some platforms but barely-just-right on others.

**Comment by csadilek** [comment] 2017-06-15 18:18
@dholbert thanks for reporting this. I've tried the latest activity stream (1.14.0-dev-) on Ubuntu 16.04.2 and can't reproduce this. The CSS should be improved either way but I'd want to be able to reproduce the problem.

Would you be able to try with the latest activity stream version [1] and share details about your OS in case the problem is still there?

[1] https://s3.amazonaws.com/moz-activity-streams-dev/dist/latest.html

**Comment by dholbert** [comment] 2017-06-15 18:40
@csadilek thanks! I can confirm the issue is fixed in that "1.14.0-dev" version of Activity Stream.

(The version I get from https://testpilot.firefox.com/experiments/activity-stream -- 1.13.0 -- is still broken, though.)

**Comment by dholbert** [comment] 2017-06-15 18:45
Just as a sanity-check, I used devtools to inspect the logo with the fixed "dev" version.  It looks like the element in question (with class `pocket-logo`) now inherits `font-size: 16px` instead of `font-size: 13px` (because it is no longer a child of the 13px-font-sized `<h3 class="section-title">`).  So it ends up  a bit larger, and large enough to avoid clipping the bottom of its background-image.

**Comment by csadilek** [comment] 2017-06-15 18:52
@dholbert thanks for confirming! I've assigned this issue to the next release as it's fixed in 1.14.0, but will also track the CSS refactoring separately. This code will be rewritten and ported to the A-S system addon: https://github.com/mozilla/activity-stream/issues/2512

**Closed by csadilek** 2017-06-15 18:52 UTC

**Comment by dholbert** [comment] 2017-06-29 22:22
Looks like I received an official Activity Stream update in the past few days (to version 1.14.0), and I can confirm this is now fixed. Thanks!
