### ISSUE TITLE
New Tab page elements are not rendered in High Contrast mode (Windows theme)

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#1562] opened 2016-10-14 14:49 UTC
[Affected versions]:
- Nightly 57.0.a1, Build ID: 20170828100127

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Activity Stream system add-on is available for a clean profile.

[Steps to reproduce]:
1. Go to High Contrast settings in Windows.
2. Choose a different theme. (High Contrast 1, High Contrast 2, High Contrast Black, High Contrast White)
3. Open the browser with the profile from prerequisites.
4. Observe the Search bar, Top Sites, Highlights and Context menu elements.

[Expected result]:
- All the elements of the page are rendered and the high contrast theme is correctly applied.

[Actual result]:
#### The Search bar:
- No search icon is visible
- The arrow is not visible in the search button and it has no hover effect.
- Search suggestions have no hover effect.
#### Top Sites and Highlights:
- The tiles have no hover effect.
- The context menu button and the options within have no icons.
- The context menu options have no hover effect.

[Additional Notes]:
**High Contrast 1**
![high contrast 1](https://user-images.githubusercontent.com/18304511/29921962-5efcb430-8e5c-11e7-9d7b-647f4cae67bb.PNG)

**Comment by jaredkerim** [comment] 2017-06-12 18:32
Closing this as a won't fix for the test pilot addon, when we are enabled in nightly for the system addon we can deal with this more appropriately as an accessbility feature.

**Comment by Softvision-VladBacia** [comment] 2017-08-28 15:44
Reopening this issue due to the fact that the add-on has entered Nightly and the issues related to High Contrast mode are still reproducible.

**Comment by Softvision-VladBacia** [comment] 2017-08-28 15:47
Removed tags in order to retriage this issue.

**Comment by SoftVision-CiprianMuresan** [comment] 2017-08-31 12:01
Adding new screenshots of the New Tab page with each High Contrast Theme:

**High Contrast 1**
![high contrast 1](https://user-images.githubusercontent.com/18304511/29921962-5efcb430-8e5c-11e7-9d7b-647f4cae67bb.PNG)

**High Contrast 2**
![high contrast 2](https://user-images.githubusercontent.com/18304511/29921970-65c65bf4-8e5c-11e7-93c2-a15b6feb8779.PNG)

**High Contrast Black**
![high contrast black](https://user-images.githubusercontent.com/18304511/29921975-69f779d8-8e5c-11e7-954a-395a83da66ad.PNG)

**High Contrast White**
![high contrast white](https://user-images.githubusercontent.com/18304511/29921979-6ef4af1e-8e5c-11e7-9673-dc62e5179e48.PNG)

**Comment by Mardak** [comment] 2017-08-31 17:00
So it does look like the various icons aren't being rendered in high contrast. Even toolbar icons in "High Contrast White" are gone…

**Comment by aaronrbenson** [comment] 2017-10-25 20:03
It looks like Windows provides a guideline in the contrast setting itself for what the styles should be. I talked to Stephen about this and he suggested reaching out to someone on the desktop side (Dao, or Gijs, or Johan) for how to best handle this. I'm most confused about why the images don't show up. Other than that following the theme guidelines themselves should resolve this.

**Comment by Mardak** [comment] 2017-10-25 20:06
Sounds like in general, css `background-image`s just don't load in high contrast mode (on windows(?))

**Comment by aaronrbenson** [comment] 2017-10-25 20:07
Interesting. I wonder what Edge is doing here ..
![screen shot 2017-10-25 at 3 07 05 pm](https://user-images.githubusercontent.com/139451/32020573-401f55e4-b996-11e7-9acd-f2c807eb33ca.png)

**Comment by Mardak** [comment] 2018-03-19 18:23
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1445266

**Closed by Mardak** 2018-03-19 18:23 UTC
Labels: P3
