### ISSUE TITLE
Incorrect "total_history_size" and "total_bookmarks" in the session ping

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#1914] opened 2017-01-04 15:21 UTC
Using A-S with a new profile, the payload of the session ping always has following values
```json
{
  "total_history_size": 0,
  "total_bookmarks": 10
}
```
Looks like those two fields didn't get updated properly.

**Comment by emtwo** [comment] 2017-01-04 22:04
There are usually some default bookmarks that come with a new profile. Perhaps that's where the 10 is coming from?

**Comment by sarracini** [comment] 2017-01-09 19:11
This is working as intended - the PlacesStatsFeed updates every 24h so although it looks wrong a bunch, it'll eventually correct itself. Closing this

**Closed by sarracini** 2017-01-09 19:11 UTC
