### ISSUE TITLE
Tab Tracker events are different for a regular new tab

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#1619] opened 2016-10-24 18:55 UTC
I noticed while working on tab tracker that the events emitted by `sdk/tabs` are slightly different for activity stream v.s. a regular new tab.

For an activity stream new tab the following events are dispatched, in this order:
- `open` (url is `about:blank`)
- `activate`(url is `about:blank`)
- `ready` (url is actually the new tab url)
- `pageshow` (url is actually the new tab url)

For a regular old new tab, the **first new tab that is opened** has the same events as an activity stream new tab. For **any additional new tabs**, only the following events are dispatched:
- `open` (url is actually the new tab url)
- `activate` (url is actually the new tab url)

**Comment by sarracini** [comment] 2016-10-25 17:22
After doing some digging, the events fired don't seem to affect the pings so we should be ok. Confirmed with marina that we don't really care about ```load_reason``` which is the only difference between the session pings in about:newtab and activity stream. That's the only ping that the tab events would be affecting. So I'm gonna close this, since I think we're good

**Closed by sarracini** 2016-10-25 17:22 UTC
