### ISSUE TITLE
Inconsistent site name between Top Sites and Highlights

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#1624] opened 2016-10-24 22:30 UTC
![nightly](https://cloud.githubusercontent.com/assets/557895/19666179/c1e1799a-99fd-11e6-99c1-da9b7b0845ab.png)

I noticed that the Top Sites lists the site name as "embed", whereas the Highlights section lists "embedly". Not sure if those are pulling from the same sources, or if they even need to be in sync, but it seemed slightly inconsistent.

I'm currently using a `metadataSource` of "Embedly", but that may be a red herring as I've been manually toggling between Embedly and Metadata in my about:config page.

![new_tab](https://cloud.githubusercontent.com/assets/557895/19666168/a8e28cae-99fd-11e6-88dc-af87bcb123a0.png)

![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/19666175/b2ffbce8-99fd-11e6-95b9-552efa230954.png)

---

My Top Site link is for http://embed.ly/.
### Embedly

``` json
$ http https://embedly-proxy.services.mozilla.com/v2/extract urls:='["https://embed.ly"]' -j
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 591
Content-Type: application/json
Date: Mon, 24 Oct 2016 22:27:35 GMT

{
    "error": "",
    "urls": {
        "https://embed.ly": {
            "description": "Embedly delivers the ultra-fast, easy to use products and tools for richer sites and apps.",
            "favicon_url": "http://embed.ly/static/images/favicon.ico?v=f724a",
            "images": [
                {
                    "height": 127,
                    "url": "http://embed.ly/static/images/logos/logo_color.png?v=4b245",
                    "width": 399
                }
            ],
            "original_url": "https://embed.ly",
            "provider_display": "embed.ly",
            "provider_name": "Embedly",
            "provider_url": "http://embed.ly",
            "title": "Embedly makes your content more engaging and easier to share | Embedly",
            "type": "html",
            "url": "http://embed.ly/"
        }
    }
}
```
### Metadata

``` json
$ http https://embedly-proxy.services.mozilla.com/v2/metadata urls:='["https://embed.ly"]' -j

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 498
Content-Type: application/json
Date: Mon, 24 Oct 2016 22:27:16 GMT

{
    "error": "",
    "urls": {
        "https://embed.ly": {
            "description": "Embedly delivers the ultra-fast, easy to use products and tools for richer sites and apps.",
            "favicon_url": "https://embed.ly/static/images/apple-touch-icon-144x144.png?v=5d8bb",
            "images": [
                {
                    "height": 127,
                    "url": "http://embed.ly/static/images/logos/logo_color.png?v=4b245",
                    "width": 399
                }
            ],
            "original_url": "https://embed.ly",
            "title": "Embedly makes your content more engaging and easier to share | Embedly",
            "url": "https://embed.ly"
        }
    }
}
```

**Comment by sarracini** [comment] 2016-10-25 13:35
Yeah, the highlight's name is a new feature - it uses the ```provider_name```. Topsites uses a some kind of generated name that comes from here: https://github.com/mozilla/activity-stream/blob/master/content-src/selectors/siteMetadataSelectors.js#L15.

So I think this is by design, but you're right, we should consolidate these and maybe use ```provider_name``` in topsites. We should ask for some design feedback here from @bryanbell, @aaronrbenson or @nchapman

**Comment by dmose** [comment] 2016-10-26 16:14
Yeah, highlights uses provider_name or nothing:

https://github.com/mozilla/activity-stream/blob/master/content-src/components/Spotlight/Spotlight.js#L48

We might want a utility method that computes the right thing so that we don't have a number of different variants.

CC @jaredkerim

**Comment by jaredkerim** [comment] 2017-04-17 18:55
We no longer use the 'provider_name' field when we show the name in a highlight, we compute it internally using a URL transformation, so we are dropping provider as a metadata field requirement altogether.  Closing this.

**Closed by jaredkerim** 2017-04-17 18:55 UTC
Labels: P3
