### ISSUE TITLE
sendAsyncMessage is undefined when setting about:home

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#2790] opened 2017-06-28 21:28 UTC
(system-addon) On a cold start, if you set your start page to point to about:newtab, and start nightly, there is an error that the RemotePageManager has likely not been initialized yet and we're trying to send the message to load up activity stream's data. 
Likely the event that we're listening to when initializing activity stream (in bootstrap.js) is happening too soon for about:home.

cc @k88hudson

**Comment by Mardak** [comment] 2017-08-08 19:06
Dupe of #3054 and fixed

**Closed by Mardak** 2017-08-08 19:06 UTC
Labels: fx57, P1
