### ISSUE TITLE
Perma-orange: browser_UITour_showNewTab.js "NS_ERROR_NOT_INITIALIZED nsIMessageSender.sendAsyncMessage"

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2745] opened 2017-06-20 22:08 UTC
A number of tests are failing with:

```
A promise chain failed to handle a rejection: Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage] - rejection date: Tue Jun 20 2017 21:33:40 GMT+0000 (UTC) - stack: null - false == true - JS frame :: resource://testing-common/PromiseTestUtils.jsm :: assertNoUncaughtRejections :: line 257
Stack trace:
resource://testing-common/PromiseTestUtils.jsm:assertNoUncaughtRejections:257
chrome://mochikit/content/browser-test.js:Tester_execTest/<:801
Tester_execTest@chrome://mochikit/content/browser-test.js:774:9
Tester.prototype.nextTest</<@chrome://mochikit/content/browser-test.js:686:7
SimpleTest.waitForFocus/waitForFocusInner/focusedOrLoaded/<@chrome://mochikit/content/tests/SimpleTest/SimpleTest.js:795:59
```

https://treeherder.mozilla.org/logviewer.html#?job_id=108665058&repo=pine&lineNumber=3281

Some tests have a recent console error message:
```
Console message: [JavaScript Error: "No marks with the name browser-open-newtab-start" {file: "resource://activity-stream/common/PerfService.jsm" line: 86}]
getMostRecentAbsMarkStartByName@resource://activity-stream/common/PerfService.jsm:86:13
addSession@resource://activity-stream/lib/TelemetryFeed.jsm:71:7
onAction@resource://activity-stream/lib/TelemetryFeed.jsm:182:9
_middleware/</</<@resource://activity-stream/lib/Store.jsm:57:45
_middleware/</<@resource://activity-stream/lib/Store.jsm:57:7
Store/</this[method]<@resource://activity-stream/lib/Store.jsm:35:36
onActionFromContent@resource://activity-stream/lib/ActivityStreamMessageChannel.jsm:91:5
onMessage@resource://activity-stream/lib/ActivityStreamMessageChannel.jsm:196:5
callListeners@resource://gre/modules/RemotePageManager.jsm:35:9
portMessageReceived@resource://gre/modules/RemotePageManager.jsm:110:5
callListeners@resource://gre/modules/RemotePageManager.jsm:35:9
ChromeMessagePort.prototype.message@resource://gre/modules/RemotePageManager.jsm:344:3
```

@dmose is the recently added mark for "browser-open-newtab-start" supposed to be triggering here? And perhaps tests are opening tabs in a way that it's not expecting?

**Comment by Mardak** [comment] 2017-06-20 22:17
Actually, might not be related to marking. Test is failing from before that.

**Comment by Mardak** [comment] 2017-06-20 23:47
Looks like something has been throwing/rejecting for a while. Not too interestingly is that the test started to fail when it was added 2 days ago:
https://hg.mozilla.org/mozilla-central/rev/3b544d62b767
https://bugzilla.mozilla.org/show_bug.cgi?id=1242505

**Comment by dmose** [comment] 2017-06-20 23:58
I would guess this regression was caused by #2539, the perf stuff that I landed on Friday.  #2728 
is already filed to deal with part of this problem.  My guess is that some UITour tests are opening tabs without going through BrowserOpenTab, which is triggering the underflow.  In addition to fixing #2728, we may want to add a load_trigger_type to this code path to see how it performs as well.

**Comment by Mardak** [comment] 2017-06-21 00:08
@k88hudson I tracked down the `sendAsyncMessage` call to `ActivityStreamMessageChannel`.

Here's the test output printing out the call stack just before `sendAsyncMessage` and after if it didn't throw:

```
9 INFO TEST-PASS | browser/components/uitour/test/browser_UITour_showNewTab.js | Loaded about:newtab - 
10 INFO == Done test, doing shared checks before teardown ==
GECKO(17355) | target send before
GECKO(17355) | send@resource://activity-stream/lib/ActivityStreamMessageChannel.jsm:117:35
GECKO(17355) | middleware/</<@resource://activity-stream/lib/ActivityStreamMessageChannel.jsm:76:9
GECKO(17355) | _middleware/</<@resource://activity-stream/lib/Store.jsm:56:7
GECKO(17355) | Store/</this[method]<@resource://activity-stream/lib/Store.jsm:35:36
GECKO(17355) | onAction@resource://activity-stream/lib/NewTabInit.jsm:19:9
GECKO(17355) | _middleware/</</<@resource://activity-stream/lib/Store.jsm:57:45
GECKO(17355) | _middleware/</<@resource://activity-stream/lib/Store.jsm:57:7
GECKO(17355) | Store/</this[method]<@resource://activity-stream/lib/Store.jsm:35:36
GECKO(17355) | onActionFromContent@resource://activity-stream/lib/ActivityStreamMessageChannel.jsm:91:5
GECKO(17355) | onNewTabLoad@resource://activity-stream/lib/ActivityStreamMessageChannel.jsm:169:5
GECKO(17355) | callListeners@resource://gre/modules/RemotePageManager.jsm:35:9
GECKO(17355) | portMessageReceived@resource://gre/modules/RemotePageManager.jsm:110:5
GECKO(17355) | callListeners@resource://gre/modules/RemotePageManager.jsm:35:9
GECKO(17355) | ChromeMessagePort.prototype.message@resource://gre/modules/RemotePageManager.jsm:344:3
GECKO(17355) | target send after
11 INFO TEST-PASS | browser/components/uitour/test/browser_UITour_showNewTab.js | Element should not be null, when checking visibility - 
12 INFO TEST-PASS | browser/components/uitour/test/browser_UITour_showNewTab.js | Highlight should be closed/hidden after UITour tab is closed - 
13 INFO TEST-PASS | browser/components/uitour/test/browser_UITour_showNewTab.js | Element should not be null, when checking visibility - 
14 INFO TEST-PASS | browser/components/uitour/test/browser_UITour_showNewTab.js | Tooltip should be closed/hidden after UITour tab is closed - 
15 INFO TEST-PASS | browser/components/uitour/test/browser_UITour_showNewTab.js | @noautohide on the menu panel should have been cleaned up - 
16 INFO TEST-PASS | browser/components/uitour/test/browser_UITour_showNewTab.js | The panel shouldn't have @panelopen - 
17 INFO TEST-PASS | browser/components/uitour/test/browser_UITour_showNewTab.js | The panel shouldn't be open - 
18 INFO TEST-PASS | browser/components/uitour/test/browser_UITour_showNewTab.js | Menu button should know that the menu is closed - 
19 INFO Done shared checks
20 INFO Leaving test bound test_aboutNewTab
GECKO(17355) | target send before
GECKO(17355) | send@resource://activity-stream/lib/ActivityStreamMessageChannel.jsm:117:35
GECKO(17355) | middleware/</<@resource://activity-stream/lib/ActivityStreamMessageChannel.jsm:76:9
GECKO(17355) | _middleware/</<@resource://activity-stream/lib/Store.jsm:56:7
GECKO(17355) | Store/</this[method]<@resource://activity-stream/lib/Store.jsm:35:36
GECKO(17355) | refresh@resource://activity-stream/lib/TopSitesFeed.jsm:59:5
GECKO(17355) | async*onAction@resource://activity-stream/lib/TopSitesFeed.jsm:79:11
GECKO(17355) | _middleware/</</<@resource://activity-stream/lib/Store.jsm:57:45
GECKO(17355) | _middleware/</<@resource://activity-stream/lib/Store.jsm:57:7
GECKO(17355) | Store/</this[method]<@resource://activity-stream/lib/Store.jsm:35:36
GECKO(17355) | onActionFromContent@resource://activity-stream/lib/ActivityStreamMessageChannel.jsm:91:5
GECKO(17355) | onNewTabLoad@resource://activity-stream/lib/ActivityStreamMessageChannel.jsm:169:5
GECKO(17355) | callListeners@resource://gre/modules/RemotePageManager.jsm:35:9
GECKO(17355) | portMessageReceived@resource://gre/modules/RemotePageManager.jsm:110:5
GECKO(17355) | callListeners@resource://gre/modules/RemotePageManager.jsm:35:9
GECKO(17355) | ChromeMessagePort.prototype.message@resource://gre/modules/RemotePageManager.jsm:344:3
21 INFO TEST-UNEXPECTED-FAIL | browser/components/uitour/test/browser_UITour_showNewTab.js | A promise chain failed to handle a rejection: Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage] - rejection date: Tue Jun 20 2017 16:57:04 GMT-0700 (PDT) - stack: null - false == true - JS frame :: resource://testing-common/PromiseTestUtils.jsm :: assertNoUncaughtRejections :: line 257
```

In particular, the first stack includes `onAction@resource://activity-stream/lib/NewTabInit.jsm:19:9` while the latter has `async*onAction@resource://activity-stream/lib/TopSitesFeed.jsm:79:11`

My guess is that the target is in the process of being removed and `NewTabInit` happens to be fast enough but `TopSitesFeed` isn't. I do see that there's a `if (!target)` check, so maybe we just wrap it in a `try` instead of checking `target`.

**Closed** 2017-06-21 17:01 UTC
Labels: Fx / Pref on in Nightly, Graduation, MVP, P1
