### ISSUE TITLE
Topsite text is misaligned after deleting cards

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#2076] opened 2017-01-25 16:21 UTC
<img width="840" alt="image" src="https://cloud.githubusercontent.com/assets/25276/22298914/36add0d0-e2f0-11e6-9365-8c499a309071.png">

Hit newtab, then delete four or five topsite cards.

**Comment by Softvision-VladBacia** [comment] 2017-01-26 08:39
Also, I have encountered this issue with the following scenario:

**[Affected versions]:**
-latest Firefox release v50.1.0
-Activity Stream Pre-release 1.3.0-pre-release-1485356001-8b433f9

**[Affected Platforms]:**
-All Windows
-All Mac OS X
-All Linux

**[Prerequisites]:**
-Latest Activity Stream Pre-release add-on version (1.3.0-pre-release) was previously installed on a profile.
-From about:config, only the "extensions.@activity-streams.experiments.screenshots" experiment is set to true.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Open AS New Tab and observe the Top Sites card titles.

**[Expected result]:**
-Top Sites card titles are in line with the cards.

**[Actual result]:**
-Top Sites card titles are displayed  slightly to the right.

**[Notes]:**
- [Here](https://drive.google.com/open?id=0B6QogV2AJFKiaFV3OV9JSVJNbVU) is a video with the issue.
- Here is a screenshot with the issue:
![text is misaligned for top sites cards](https://cloud.githubusercontent.com/assets/9248513/22324715/7c19b1c0-e3b3-11e6-8272-e44b6d55375b.jpg)

**Comment by rlr** [comment] 2017-01-27 20:17
fix for this landed ^^

**Closed by rlr** 2017-01-27 20:17 UTC
Labels: Bug, MVP, P1

**Comment by Softvision-VladBacia** [comment] 2017-01-30 15:27
The issue is no longer reproducible on the latest Activity Stream 1.3.0-pre-release-1485545108-d43cc0c.
