### ISSUE TITLE
High CPU usage on newtab

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/activity-stream#2732] opened 2017-06-18 17:03 UTC
Copying over a report from Discourse:

https://discourse.mozilla-community.org/t/high-cpu-use-on-new-tab/16455

---

> I've had Activity Stream enabled for quite some time on my browser (Beta channel). Just today I realized that when I opened a new tab, then watched the two Firefox processes, they combined to use around 50-75% CPU while doing nothing. If I loaded a webpage then let the browser sit, CPU use drops to near zero.
>
> I disabled Activity Stream and this behaviour wasn't present any more. I re-enabled Activity Stream, and the problem seems to have gone away.
>
> Definitely not of "bug report" caliber, but maybe a point of interest for someone. Maybe it's happening to other people and they're not realizing it.
>
> Running OS X 10.11.6 and Firefox 55.0b1

---

> Hi
>
> Thank you for posting this, I am seeing the same thing although I initially thought it was to do with e10s. I toggled the Multi-process option in about:preferances and after a couple of browser restarts everything seemed to be fine. Having read what you have written, I have disabled Activity Stream and CPU utilisation is much calmer from the start (and with a bit less fan noise!).
>
> Running TeaLinuxOS 8 and Nightly 56.0a1.

**Comment by jaredkerim** [comment] 2017-06-19 18:17
@chuckharmston Thanks for forwarding this.  There is a significant performance impact from running the test pilot version of the addon (the one currently in use).  Because of this we are rewriting activity stream from scratch as a system addon with performance regressions as a number one concern, however we will not be modifying the test pilot version, it is being retired when the system addon is preffed on in nightly, so I am closing this.

**Closed by jaredkerim** 2017-06-19 18:17 UTC
