### ISSUE TITLE
Won't Enable

### ISSUE THREAD

**Issue by Tyman691** [mozilla/activity-stream#718] opened 2016-05-17 20:12 UTC
![activity stream](https://cloud.githubusercontent.com/assets/19416409/15337512/65331394-1c39-11e6-9ea4-86fd5451fbcf.JPG)
Activity Stream will not enable.
Clicked "enable activity stream" button, button changed to say "enabling." Button stuck on "enabling"
Screen shot attached.

**Comment by pdehaan** [comment] 2016-05-17 22:21
@Tyman691 Thanks for the bug report!
I believe this is a dupe of the following **Test Pilot** issue: https://github.com/mozilla/testpilot/issues/843, which we're currently investigating.

Closing this in favor of the upstream Test Pilot bug.

**Closed by pdehaan** 2016-05-17 22:21 UTC
