### ISSUE TITLE
Bug 1282714 - "Delete from History" and "Dismiss" options are no longer available in the "..." context menu from Activity Stream Timeline History and New Tab pages, for a bookmarked item

### ISSUE THREAD

**Issue by SoftVision-VladBacia** [mozilla/activity-stream#887] opened 2016-06-28 09:08 UTC
via https://bugzilla.mozilla.org/show_bug.cgi?id=1282714
<hr>
Affected versions]:
- Firefox 45.0 and up
- Activity Stream v1.1.0

[Affected Platforms]:
- All Windows
- All Linux
- All Mac OS

[Prerequisites]:
- Latest Activity Stream add-on (v1.1.0-dev) was previously installed on a profile.
- Have enough history so that the "Top Sites", "Highlights", "History" areas are populated with visited websites.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the Activity Stream button from the browser toolbar.
3. Hover a Highlights tile and click on "..." context menu button.
4. Click on "Bookmark" button.
5. Hover again the previously bookmarked Highlights tile and click on "..." context menu button.
6. Observe the options displayed.

[Expected result]:
- "Delete from History" and "Dismiss" options are displayed in the context menu for the bookmarked website.

[Actual result]:
- After a website is bookmarked the "Delete from History" and "Dismiss" options are no longer available in Activity Stream Timeline History and New Tab pages.

[Notes]:
- This issue has appear after fixing #859 .
- This issue is reproducible in Activity Stream Timeline History page and Activity Stream New Tab page, for items from "Top Sites", "Highlights" and "History" areas, that were bookmarked.
- [Here](https://bug1282714.bmoattachments.org/attachment.cgi?id=8765798) is a screen recording of the issue.

**Comment by sarracini** [comment] 2016-06-28 14:54
I thought the intention was to remove those options for bookmarked items. That's what #859 was meant to do. I believe this is by design

**Comment by SoftVision-VladBacia** [comment] 2016-06-28 15:19
Yes, but #859 was referring only to Bookmarks History page. 
As a user I want to be able to "Delete from History" or "Dismiss" bookmarked and non-bookmarked items, from Timeline History page and New Tab page. 
The "Delete from History" option doesn't make sense in Bookmarks History page.

**Comment by sarracini** [comment] 2016-06-28 15:39
Ahh so like this?

- bookmarked + timeline/newtab pages = you can delete/dismiss 
- bookmarked + bookmarks history page = you can't delete/dismiss

**Comment by sarracini** [comment] 2016-06-28 16:12
Fixed with #889

**Closed by sarracini** 2016-06-28 16:12 UTC
Labels: Has PR

**Comment by SoftVision-VladBacia** [comment] 2016-06-29 08:32
This issue has been verified on Win 8.1 x64, Mac OS X 10.11 and Ubuntu 14.04 x64 with latest Nightly 50.0a1 (Build ID: 20160628030238) using latest Activity Stream v1.1.0-custom build and could not reproduce it.
Thus, marking this issue as Verified-Fixed.
