### ISSUE TITLE
Letter "g" is truncated in the AS Search text box

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#2079] opened 2017-01-25 17:43 UTC
**[Affected versions]:**
-Firefox 45.0 and up
-Activity Stream Pre-release 1.3.0-pre-release-1485308519-0fda037

**[Affected Platforms]:**
-All Windows

**[Prerequisites]:**
-Latest Activity Stream Pre-release add-on version (1.3.0-pre-release) was previously installed on a profile.
-From about:config, only the "extensions.@activity-streams.experiments.screenshots" experiment is set to true.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Open AS New Tab page.
3. Type g letter in the Search text box.
4. Observe the letter.

**[Expected result]:**
-Letter "g" is fully displayed in the Search text box.

**[Actual result]:**
-The letter "g" is truncated in the Search text box. The lower part is not fully visible.

**[Notes]:**
- This issue may affect other keyboard styles from other languages
- Here is a screenshot with the issue:
![letter g is truncated](https://cloud.githubusercontent.com/assets/9248513/22302153/3c9c760e-e336-11e6-8ce8-3d10269c6221.jpg)

**Comment by rlr** [comment] 2017-01-25 23:57
I'm unable to reproduce this on OS-X. I'll try windows next.

<img width="751" alt="screen shot 2017-01-25 at 6 55 23 pm" src="https://cloud.githubusercontent.com/assets/36629/22314530/0a0f5d60-e330-11e6-890e-9f736504d03a.png">

**Comment by sarracini** [comment] 2017-01-27 14:25
Fixed with #2086

**Closed by sarracini** 2017-01-27 14:25 UTC
Labels: Has PR, MVP, P1, Regression, Release / Blocking

**Comment by Softvision-VladBacia** [comment] 2017-01-27 16:24
The issue is no longer reproducible on the latest Activity Stream Pre-release v1.3.0-pre-release-1485468410-8683703.
