### ISSUE TITLE
 Create an "ignore list" of domains/links?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#479] opened 2016-04-06 19:26 UTC
I was just testing installing Activity Stream via Test Pilot with a brand new Firefox profile, and noticed something a bit funny in my Activity Stream feed.

You can see in the screenshot below that it stores history results for stable.dev.lcip.org (and it's _/oauth/_ and _/oauth/signup/_ routes). Not sure if we want to consider creating some curated list of domains/routes that we never want to appear in people's feeds, or if that's overkill.

![new_tab](https://cloud.githubusercontent.com/assets/557895/14329840/3e45b4b0-fbf2-11e5-999b-0fa36cac5eba.png)

**Comment by sarracini** [comment] 2016-05-16 14:17
possibly a dupe of #178

**Comment by pdehaan** [comment] 2016-05-16 16:16
> possibly a dupe of #178

I don't think so. #178 deals with us not showing any results for some naughty maliciousdomain.com which Google/Firefox reports as potentially unsafe (would affect all users).
This issue deals with "I'm getting really sick of seeing results from Gmail.com in my feed, so let me block that domain from Activity Stream" (would affect only me).

**Comment by pdehaan** [comment] 2016-05-26 00:30
OK, much better use case which I noticed today and cannot unnotice:

1. Do a search using Yahoo! as your search provider.
2. Search for "beans" (or whatever).
3. Click on the top link (or Wikipedia, or whatever your preferred source of bean information is).
4. Open Activity Stream (new tab or timeline view)

### Actual results
I have three items in my timeline:

1. https://search.yahoo.com/yhs/search?p=beans&ei=UTF-8&hspart=mozilla&hsimp=yhs-002 (my original search for "beans")
2. http://r.search.yahoo.com/_ylt=A86.J3UCQkZXOzAAfh4nnIlQ;_ylu=X3oDMTEyMHVqMzd1BGNvbG8DZ3ExBHBvcwMxBHZ0aWQDQjIwNDRfMQRzZWMDc3I-/RV=2/RE=1464251011/RO=10/RU=https%3a%2f%2fen.wikipedia.org%2fwiki%2fBean/RK=0/RS=GKKrRc9nz_oVYE_XnllQ4UVpWvg- (some hideous nonsense of a redirect URL which takes me to wikipedia -- Note that I never "saw" this page, its just some interstitial that Yahoo! probably uses for profiling and stats collection)
3. https://en.wikipedia.org/wiki/Bean (the Yahoo! search page result that I clicked).

In this case (or any case) I can't imagine why I (a user) would want "http://r.search.yahoo.com" in my timeline or activity feed. [nit: I double can't imagine why it bounced me from HTTPS to vanilla HTTP back to HTTPS.]

**Comment by jaredkerim** [comment] 2016-07-05 17:28
Closing this for now, if we want to revisit the idea of hiding a certain class of URLs we can in the future.

**Closed by jaredkerim** 2016-07-05 17:28 UTC
